/**
 * Regression tests for multi-page scanned financial documents.
 *
 * Covers:
 * 1. Page order detection and reordering (upload in reverse order)
 * 2. Chunk marker removal ("Страница X/Y" generated by translator)
 * 3. Financial block classification (line items vs totals vs tax summary)
 * 4. Wide table rendering: landscape section, column widths, no word-split
 * 5. Summary blocks are separate (not inside 8-column item grid)
 * 6. Required values preserved in DOCX XML
 * 7. Legal entity names not converted to ООО/ТОО
 * 8. No document AST calls
 *
 * The specific document used for fixtures is a sanitised 2-page receipt-style
 * financial document. Production logic must NOT depend on Thai language,
 * specific brand names, or specific numeric values.
 */

// Mock env before any module that imports it
jest.mock('../env', () => ({
  env: {
    APP_ENV: 'staging',
    NEXT_PUBLIC_SUPABASE_URL: 'https://test.supabase.co',
    SUPABASE_SERVICE_ROLE_KEY: 'test-key',
    R2_ACCOUNT_ID: 'r2', R2_ACCESS_KEY_ID: 'k', R2_SECRET_ACCESS_KEY: 's', R2_BUCKET_NAME: 'b',
    ANTHROPIC_API_KEY: 'test', MISTRAL_API_KEY: 'test',
    RESEND_API_KEY: undefined, SITE_URL: 'https://test.example.com',
    EMAILS_ENABLED: false, EMAIL_REDIRECT_ALL_TO: undefined,
    PAYMENTS_MODE: 'test', OFFICIAL_WORKFLOW_ENABLED: true,
    POLL_INTERVAL_MS: 10000, WORKER_CONCURRENCY: 1,
  },
}));

import { execSync } from 'child_process';
import fs from 'fs';
import os from 'os';
import path from 'path';
import { renderToDocx, LANDSCAPE_WIDTH_DXA } from '../docx-renderer';
import { reorderPagesByEvidence, detectPageEvidence } from '../page-order';
import { classifyFinancialBlock, computeLineItemColumnWidths } from '../financial-blocks';
import { stripInternalChunkMarkersForTest } from '../translator';

// ── Helpers ───────────────────────────────────────────────────────────────────

async function getDocxXml(buf: Buffer): Promise<string> {
  const tmp = path.join(os.tmpdir(), `wpo-fin-${Date.now()}.docx`);
  try {
    fs.writeFileSync(tmp, buf);
    return execSync(`unzip -p "${tmp}" "word/document.xml"`).toString();
  } finally {
    try { fs.unlinkSync(tmp); } catch { /* ignore */ }
  }
}

function extractPlainText(xml: string): string {
  return xml.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ');
}

const RENDER_META = {
  sourceLang: 'th',
  targetLang: 'ru',
  translatedAt: '2026-06-18',
  filename: 'receipt_test.jpg',
  serviceLevel: 'official_with_translator_signature_and_provider_stamp' as const,
  outputMode: 'translator_review_draft' as const,
  documentType: 'other',
};

// ── §1: Page order detection ──────────────────────────────────────────────────

describe('page order detection', () => {
  it('detects English page marker "Page 1 of 2"', () => {
    const ev = detectPageEvidence('Some content\nPage 1 of 2\nMore content', 0);
    expect(ev.detectedPageNumber).toBe(1);
    expect(ev.detectedTotalPages).toBe(2);
    expect(ev.confidence).toBeGreaterThan(0.8);
  });

  it('detects Thai page marker "หน้า 1 จาก 2"', () => {
    const ev = detectPageEvidence('เนื้อหา\nหน้า 2 จาก 2\n', 0);
    expect(ev.detectedPageNumber).toBe(2);
    expect(ev.detectedTotalPages).toBe(2);
  });

  it('detects Russian page marker "Страница 2 из 2"', () => {
    const ev = detectPageEvidence('Содержание\nСтраница 2 из 2', 0);
    expect(ev.detectedPageNumber).toBe(2);
    expect(ev.detectedTotalPages).toBe(2);
  });

  it('reorders pages when uploaded in reverse order', () => {
    // Simulate: uploaded page 2 first, then page 1
    const page2 = 'Invoice header\nPage 2 of 2\nItem table here';
    const page1 = 'Company header\nPage 1 of 2\nDate: 2026-01-15';

    const result = reorderPagesByEvidence([page2, page1]);
    expect(result.reordered).toBe(true);
    // After reorder: first markdown should be page1 content
    expect(result.reorderedMarkdowns[0]).toContain('Company header');
    expect(result.reorderedMarkdowns[1]).toContain('Invoice header');
  });

  it('does not reorder when pages are already in order', () => {
    const page1 = 'Content\n1 of 2';
    const page2 = 'Content\n2 of 2';
    const result = reorderPagesByEvidence([page1, page2]);
    expect(result.reordered).toBe(false);
    expect(result.reorderedMarkdowns[0]).toBe(page1);
  });

  it('does not reorder when page numbers are ambiguous (duplicate)', () => {
    const p1 = 'Content\nPage 1 of 2';
    const p2 = 'Content\nPage 1 of 2'; // duplicate
    const result = reorderPagesByEvidence([p1, p2]);
    expect(result.reordered).toBe(false);
    expect(result.warning).toBe('PAGE_ORDER_DUPLICATE_NUMBERS');
  });

  it('does not reorder when detection partial', () => {
    const p1 = 'Content\nPage 1 of 2';
    const p2 = 'No page number here';
    const result = reorderPagesByEvidence([p1, p2]);
    expect(result.reordered).toBe(false);
    expect(result.warning).toBe('PAGE_ORDER_DETECTION_PARTIAL');
  });

  it('single page: no reorder', () => {
    const result = reorderPagesByEvidence(['Single page content']);
    expect(result.reordered).toBe(false);
    expect(result.reorderedMarkdowns).toHaveLength(1);
  });
});

// ── §2: Chunk marker removal ──────────────────────────────────────────────────

describe('chunk marker removal', () => {
  it('strips standalone "Страница 1/4" from translation output', () => {
    const input = 'Line 1\nСтраница 1/4\nLine 3';
    expect(stripInternalChunkMarkersForTest(input)).not.toContain('Страница 1/4');
    expect(stripInternalChunkMarkersForTest(input)).toContain('Line 1');
    expect(stripInternalChunkMarkersForTest(input)).toContain('Line 3');
  });

  it('strips standalone "Page 3/5" from translation output', () => {
    const input = 'Content before\nPage 3/5\nContent after';
    const out = stripInternalChunkMarkersForTest(input);
    expect(out).not.toContain('Page 3/5');
    expect(out).toContain('Content before');
    expect(out).toContain('Content after');
  });

  it('strips "Chunk 2/4" marker', () => {
    const input = 'Before\nChunk 2/4\nAfter';
    expect(stripInternalChunkMarkersForTest(input)).not.toContain('Chunk 2/4');
  });

  it('preserves "Page 1 of 2" (source content, not chunk marker)', () => {
    const input = 'Footer text: Page 1 of 2';
    // "Page 1 of 2" uses "of", not "/" — not a chunk marker
    expect(stripInternalChunkMarkersForTest(input)).toContain('Page 1 of 2');
  });

  it('preserves "Страница 1 из 2" (source content)', () => {
    const input = 'Страница 1 из 2';
    expect(stripInternalChunkMarkersForTest(input)).toContain('Страница 1 из 2');
  });

  it('does not strip partial matches inside prose', () => {
    const input = 'The document has 3/4 of the required pages.';
    // "3/4" in middle of sentence — not a standalone marker
    expect(stripInternalChunkMarkersForTest(input)).toContain('3/4');
  });
});

// ── §3: Financial block classification ───────────────────────────────────────

describe('financial block classification', () => {
  it('classifies 8-column table as line_items (wide)', () => {
    const headers = ['#', 'Article', 'Description', 'Qty', 'Unit', 'Price', 'VAT', 'Total'];
    const rows = Array.from({ length: 10 }, (_, i) => [
      String(i + 1), `ART-${i}`, `Product description ${i}`, '5', 'pcs', '100.00', '7%', '500.00',
    ]);
    const result = classifyFinancialBlock(headers, rows);
    expect(result.kind).toBe('line_items');
    expect(result.isWide).toBe(true);
    expect(result.columnCount).toBe(8);
  });

  it('classifies 7-column table as line_items (wide)', () => {
    const headers = ['#', 'Description', 'Qty', 'Unit', 'Price', 'VAT', 'Total'];
    const rows = Array.from({ length: 5 }, (_, i) => [
      String(i + 1), `Item ${i}`, '10', 'pcs', '50.00', '7%', '500.00',
    ]);
    const result = classifyFinancialBlock(headers, rows);
    expect(result.isWide).toBe(true);
  });

  it('classifies VAT table as tax_summary', () => {
    const headers = ['VAT code', 'Tax base', 'VAT amount', 'Gross'];
    const rows = [['7%', '2,716.70', '190.17', '2,906.87'], ['Exempt', '192.17', '0.00', '192.17']];
    const result = classifyFinancialBlock(headers, rows);
    expect(result.kind).toBe('tax_summary');
    expect(result.isWide).toBe(false);
  });

  it('classifies narrow label+amount table as totals', () => {
    const headers = ['Item', 'Amount'];
    const rows = [
      ['Total', '2,955.25'],
      ['Discount', '0.00'],
      ['Net amount', '2,955.25'],
    ];
    const result = classifyFinancialBlock(headers, rows);
    expect(result.kind).toBe('totals');
    expect(result.isWide).toBe(false);
  });

  it('classifies payment breakdown table', () => {
    const headers = ['POD', 'Coupon', 'Voucher', 'Total'];
    const rows = [['0.00', '0.00', '0.00', '2,955.25']];
    const result = classifyFinancialBlock(headers, rows);
    expect(result.kind).toBe('payment_breakdown');
    expect(result.isWide).toBe(false);
  });
});

// ── §4: Column width computation ──────────────────────────────────────────────

describe('line item column widths', () => {
  it('returns 8 widths summing close to landscape width for 8-col table', () => {
    const widths = computeLineItemColumnWidths(8, LANDSCAPE_WIDTH_DXA);
    expect(widths).toHaveLength(8);
    const sum = widths.reduce((a, b) => a + b, 0);
    expect(sum).toBeCloseTo(LANDSCAPE_WIDTH_DXA, -2);
    // Description column (index 2) should be the widest
    expect(widths[2]).toBeGreaterThan(widths[0]!);
    expect(widths[2]).toBeGreaterThan(widths[3]!);
    expect(widths[2]).toBeGreaterThan(widths[4]!);
  });

  it('returns 7 widths for 7-col table', () => {
    const widths = computeLineItemColumnWidths(7, LANDSCAPE_WIDTH_DXA);
    expect(widths).toHaveLength(7);
  });

  it('returns equal widths for generic column count', () => {
    const widths = computeLineItemColumnWidths(5, 10000);
    expect(widths).toHaveLength(5);
    expect(widths.every(w => w === 2000)).toBe(true);
  });
});

// ── §5: Sanitised two-page receipt fixture ───────────────────────────────────

/**
 * Sanitised translation of a 2-page financial document.
 * Page 1: metadata + 17 line items (8 columns)
 * Page 2: tax summary + amount in words + totals + payment breakdown + terms
 *
 * Upload order: page 2 first, then page 1.
 * After reorder: page 1 before page 2.
 *
 * All company/customer names are fictional. All numbers are fictional.
 */

const RECEIPT_PAGE1_MARKDOWN = `## Invoice

## Seller

| Field | Value |
|---|---|
| Company | Alpha Trading Public Company Limited |
| Tax ID | 1234567890123 |
| Address | 567/2, Moo 9, Tambon Ban Dua, Amphoe Mueang, Chiang Rai Province 57100, Thailand |

## Customer

| Field | Value |
|---|---|
| Customer name | Beta Retail Co., Ltd. |
| Tax ID | 9876543210987 |
| Branch | Main Office |
| Address | 100/5, Soi 15, Sukhumvit Road, Khlong Toei District, Bangkok 10110, Thailand |

## Invoice Details

| Field | Value |
|---|---|
| Invoice number | INV-2026-0001 |
| Date | 15/01/2026 |
| Page | 1 of 2 |

## Goods and Services

| # | Article | Description | Qty | Unit | Unit Price | VAT | Total |
|---|---|---|---|---|---|---|---|
| 1 | ART-001 | Fresh Tomatoes Grade A | 100 | kg | 45.00 | 7% | 4,500.00 |
| 2 | ART-002 | Potatoes Premium | 200 | kg | 22.50 | 7% | 4,500.00 |
| 3 | ART-003 | Onions Yellow | 150 | kg | 18.00 | 7% | 2,700.00 |
| 4 | ART-004 | Garlic Fresh | 50 | kg | 65.00 | 7% | 3,250.00 |
| 5 | ART-005 | Carrots Organic | 80 | kg | 35.00 | 7% | 2,800.00 |
| 6 | ART-006 | Bell Peppers Red | 40 | kg | 90.00 | 7% | 3,600.00 |
| 7 | ART-007 | Cucumbers Fresh | 60 | kg | 28.00 | 7% | 1,680.00 |
| 8 | ART-008 | Lettuce Iceberg | 30 | bag | 75.00 | 7% | 2,250.00 |
| 9 | ART-009 | Broccoli Crown | 25 | kg | 120.00 | 7% | 3,000.00 |
| 10 | ART-010 | Spinach Baby | 15 | kg | 180.00 | 7% | 2,700.00 |
| 11 | ART-011 | Mushrooms Button | 20 | kg | 95.00 | 7% | 1,900.00 |
| 12 | ART-012 | Cauliflower | 35 | kg | 55.00 | 7% | 1,925.00 |
| 13 | ART-013 | Zucchini Green | 45 | kg | 42.00 | 7% | 1,890.00 |
| 14 | ART-014 | Eggplant Thai | 30 | kg | 38.00 | 7% | 1,140.00 |
| 15 | ART-015 | Sweet Corn | 50 | kg | 32.00 | 7% | 1,600.00 |
| 16 | ART-016 | Celery Fresh | 20 | bunch | 55.00 | 7% | 1,100.00 |
| 17 | ART-017 | Basil Sweet | 10 | kg | 250.00 | 7% | 2,500.00 |
`;

const RECEIPT_PAGE2_MARKDOWN = `## Summary

| Field | Value |
|---|---|
| Invoice number | INV-2026-0001 |
| Page | 2 of 2 |

## VAT Summary

| VAT Code | Tax Base | VAT Amount | Gross Amount |
|---|---|---|---|
| 7% | 2,908.87 | 46.38 | 2,955.25 |

## Amount in Words

| Total amount |
|---|
| Two thousand nine hundred fifty five baht twenty five satang |

## Totals

| Item | Amount |
|---|---|
| Total | 2,955.25 |
| Discount | 0.00 |
| Net Amount | 2,955.25 |

## Payment Breakdown

| Cash | Coupon | Voucher | Total Paid |
|---|---|---|---|
| 2,955.25 | 0.00 | 0.00 | 2,955.25 |

## Terms and Conditions

Goods sold are not returnable after 24 hours. Prices include VAT where applicable.

[Rectangular label: For Customer]
`;

describe('two-page receipt regression', () => {
  it('reorders pages correctly (uploaded page 2 first, then page 1)', () => {
    // Upload order: page2, page1
    const result = reorderPagesByEvidence([RECEIPT_PAGE2_MARKDOWN, RECEIPT_PAGE1_MARKDOWN]);
    expect(result.reordered).toBe(true);
    // After reorder: page1 (1 of 2) comes first
    expect(result.reorderedMarkdowns[0]).toContain('Page | 1 of 2');
    expect(result.reorderedMarkdowns[1]).toContain('Page | 2 of 2');
  });

  it('joined markdown starts with page 1 content after reorder', () => {
    const result = reorderPagesByEvidence([RECEIPT_PAGE2_MARKDOWN, RECEIPT_PAGE1_MARKDOWN]);
    const joined = result.reorderedMarkdowns.join('\n\n');
    // Page 1 content (company header) appears before page 2 content (summary)
    const page1pos = joined.indexOf('Goods and Services');
    const page2pos = joined.indexOf('VAT Summary');
    expect(page1pos).toBeGreaterThan(-1);
    expect(page2pos).toBeGreaterThan(-1);
    expect(page1pos).toBeLessThan(page2pos);
  });

  it('line-item table classified as wide line_items', () => {
    const headers = ['#', 'Article', 'Description', 'Qty', 'Unit', 'Unit Price', 'VAT', 'Total'];
    const rows = Array.from({ length: 17 }, (_, i) => [
      String(i + 1), `ART-${String(i + 1).padStart(3, '0')}`, `Product ${i + 1}`,
      '10', 'kg', '45.00', '7%', '450.00',
    ]);
    const result = classifyFinancialBlock(headers, rows);
    expect(result.kind).toBe('line_items');
    expect(result.isWide).toBe(true);
    expect(result.columnCount).toBe(8);
  });

  it('renders DOCX with 17 line items — all article codes in XML', async () => {
    const joined = [RECEIPT_PAGE1_MARKDOWN, RECEIPT_PAGE2_MARKDOWN].join('\n\n');
    const docxBuf = await renderToDocx(joined, RENDER_META, []);
    const xml = await getDocxXml(docxBuf);
    const text = extractPlainText(xml);

    // All 17 article codes must survive
    for (let i = 1; i <= 17; i++) {
      const code = `ART-${String(i).padStart(3, '0')}`;
      expect(text).toContain(code);
    }
  });

  it('DOCX XML does not contain standalone chunk marker "Страница N/M"', async () => {
    const joined = [RECEIPT_PAGE1_MARKDOWN, RECEIPT_PAGE2_MARKDOWN].join('\n\n');
    const docxBuf = await renderToDocx(joined, RENDER_META, []);
    const xml = await getDocxXml(docxBuf);
    const text = extractPlainText(xml);

    // Pattern: "Страница N/M" as standalone chunk marker
    expect(text).not.toMatch(/Страница\s+\d+\s*\/\s*\d+(?!\s+\w)/);
  });

  it('DOCX XML contains the exact fixture totals values', async () => {
    const joined = [RECEIPT_PAGE1_MARKDOWN, RECEIPT_PAGE2_MARKDOWN].join('\n\n');
    const docxBuf = await renderToDocx(joined, RENDER_META, []);
    const xml = await getDocxXml(docxBuf);
    const text = extractPlainText(xml);

    expect(text).toContain('2,908.87');
    expect(text).toContain('46.38');
    expect(text).toContain('2,955.25');
    expect(text).toContain('0.00');
  });

  it('invoice number preserved in DOCX', async () => {
    const joined = [RECEIPT_PAGE1_MARKDOWN, RECEIPT_PAGE2_MARKDOWN].join('\n\n');
    const docxBuf = await renderToDocx(joined, RENDER_META, []);
    const xml = await getDocxXml(docxBuf);
    expect(xml).toContain('INV-2026-0001');
  });

  it('legal entity not converted to ООО — "Alpha Trading Public Company Limited" preserved', async () => {
    const joined = [RECEIPT_PAGE1_MARKDOWN, RECEIPT_PAGE2_MARKDOWN].join('\n\n');
    const docxBuf = await renderToDocx(joined, RENDER_META, []);
    const xml = await getDocxXml(docxBuf);
    const text = extractPlainText(xml);

    // Should not contain fabricated ООО/ТОО conversion
    expect(text).not.toMatch(/ООО Alpha|ООО CP|ТОО Alpha/);
    // The original name should be present
    expect(text).toContain('Alpha Trading');
  });

  it('DOCX is valid and non-empty', async () => {
    const joined = [RECEIPT_PAGE1_MARKDOWN, RECEIPT_PAGE2_MARKDOWN].join('\n\n');
    const docxBuf = await renderToDocx(joined, RENDER_META, []);
    expect(docxBuf.length).toBeGreaterThan(5000);
  });
});

// ── §6: Summary blocks are separate from line-item grid ──────────────────────

describe('summary blocks separate from line-item grid', () => {
  it('VAT summary classified as tax_summary (not line_items)', () => {
    const headers = ['VAT Code', 'Tax Base', 'VAT Amount', 'Gross Amount'];
    const rows = [['7%', '2,908.87', '46.38', '2,955.25']];
    const result = classifyFinancialBlock(headers, rows);
    expect(result.kind).toBe('tax_summary');
    expect(result.isWide).toBe(false);
  });

  it('2-column totals table classified as totals', () => {
    const headers = ['Item', 'Amount'];
    const rows = [
      ['Total', '2,955.25'],
      ['Discount', '0.00'],
      ['Net Amount', '2,955.25'],
    ];
    const result = classifyFinancialBlock(headers, rows);
    expect(result.kind).toBe('totals');
    expect(result.isWide).toBe(false);
  });

  it('payment breakdown with cash/coupon/voucher classified as payment_breakdown', () => {
    const headers = ['Cash', 'Coupon', 'Voucher', 'Total Paid'];
    const rows = [['2,955.25', '0.00', '0.00', '2,955.25']];
    const result = classifyFinancialBlock(headers, rows);
    expect(result.kind).toBe('payment_breakdown');
  });
});

// ── §7: No document AST calls ─────────────────────────────────────────────────

describe('document AST not used in financial rendering', () => {
  it('renderDocxFromAst is not imported by financial-blocks', () => {
    const src = fs.readFileSync(
      path.resolve(__dirname, '../financial-blocks.ts'),
      'utf-8',
    );
    expect(src).not.toContain('renderDocxFromAst');
    expect(src).not.toContain('renderHtmlFromAst');
    expect(src).not.toContain('translateToAst');
  });

  it('page-order module does not import AST', () => {
    const src = fs.readFileSync(
      path.resolve(__dirname, '../page-order.ts'),
      'utf-8',
    );
    expect(src).not.toContain('ast');
  });
});

// ── §8: Employment certificate regression ─────────────────────────────────────

const EMPLOYMENT_CERT_MARKDOWN = `## CERTIFICATE OF EMPLOYMENT

## EMPLOYER
| Field | Value |
|---|---|
| Employer name | LLP "Stable Corp" |
| BIN | 201240012345 |
| Certificate number | CERT-2026-001 |

## EMPLOYEE
| Field | Value |
|---|---|
| Full name | TESTOVA ANNA PETROVNA |
| IIN | 930208450176 |
| Position | Senior Accountant |

## INCOME
| Calculation period | Base salary | Total gross amount | Amount payable |
|---|---|---|---|
| March 2026 | 500 000,00 KZT | 540 000,00 KZT | 437 500,00 KZT |
| April 2026 | 500 000,00 KZT | 540 000,00 KZT | 437 500,00 KZT |

[signature]
[stamp: Human Resources Department]

## Translator

I certify that this translation is complete and accurate.

Translator: ______________________
Date: ______________________
`;

describe('employment certificate regression', () => {
  it('all IIN/BIN values preserved', async () => {
    const docxBuf = await renderToDocx(EMPLOYMENT_CERT_MARKDOWN, {
      sourceLang: 'ru',
      targetLang: 'en',
      translatedAt: '2026-06-18',
      filename: 'emp.pdf',
      serviceLevel: 'official_with_translator_signature_and_provider_stamp' as const,
      documentType: 'employment_document',
    }, []);
    const xml = await getDocxXml(docxBuf);
    expect(xml).toContain('201240012345');
    expect(xml).toContain('930208450176');
    expect(xml).toContain('CERT-2026-001');
  });

  it('income table preserved (6-column not classified as wide)', async () => {
    // 4-column income table — not line_items, not wide
    const headers = ['Calculation period', 'Base salary', 'Total gross amount', 'Amount payable'];
    const rows = [['March 2026', '500 000,00 KZT', '540 000,00 KZT', '437 500,00 KZT']];
    const result = classifyFinancialBlock(headers, rows);
    expect(result.isWide).toBe(false);
  });

  it('DOCX renders without error for employment cert', async () => {
    const docxBuf = await renderToDocx(EMPLOYMENT_CERT_MARKDOWN, {
      sourceLang: 'ru',
      targetLang: 'en',
      translatedAt: '2026-06-18',
      filename: 'emp.pdf',
      serviceLevel: 'official_with_translator_signature_and_provider_stamp' as const,
      documentType: 'employment_document',
    }, []);
    expect(docxBuf.length).toBeGreaterThan(3000);
  });
});
