import type { LegalDocs } from '../types';

const LP = "Ushbu hujjatning rus tilidagi versiyasi va uning boshqa tillardagi tarjimalari o'rtasida nomuvofiqlik mavjud bo'lsa, Ijrochi tomonidan ochiq-oydin boshqa ko'rsatilmagan bo'lsa, rus tilidagi versiya ustunlikka ega.";

export const legalDocs: LegalDocs = {
  offer: {
    slug: 'offer',
    title: 'Ommaviy oferta shartnomasi',
    metaTitle: 'Ommaviy oferta — WPO Translations',
    metaDescription: "WPO Translations hujjat tarjima xizmatlari ommaviy ofertasi. Xizmat darajalari, narxlar, to'lov va qaytarish shartlari.",
    effectiveDate: '2026-05-26',
    sections: [
      { id: 'provider', heading: '1. Ijrochi haqida ma\'lumot', body: ["Ushbu Ommaviy oferta shartnomasi (keyingi o'rinlarda «Shartnoma») WorldPrimeOnline tomonidan nashr etiladi, WorldPrimeOnline  (keyingi o'rinlarda «Ijrochi») tomonidan boshqariladi.", 'Ijrochi: IE WorldPrimeOnline', 'IIN/BIN: 840324300155', "Manzil: Olmaota sh.", 'Email: worldprimeonline@gmail.com', 'Telefon: +7 701 136 63 76', 'Sayt: https://www.wpotranslations.org/', "QQS: ko'zda tutilmagan", 'Nashr sanasi: 2026-05-26', "Ushbu Shartnoma amaldagi qonunchilikka muvofiq ommaviy oferta hisoblanadi. Platformada buyurtma berish Shartnomaning barcha shartlarini to'liq va shartsiz qabul qilishni bildiradi."] },
      { id: 'definitions', heading: '2. Ta\'riflar', body: ["• «Buyurtmachi» — Platforma orqali buyurtma bergan har qanday jismoniy yoki yuridik shaxs.", "• «Xizmat» — Ijrochi tomonidan ko'rsatiladigan hujjat tarjimasi xizmatlari.", "• «Elektron tarjima» — Buyurtmachi alohida tanlamasa, tarjimon imzosi, Ijrochi muhri yoki notarial tasdiqlashsiz elektron formatda beriladigan tarjima.", "• «Rasmiy tarjima» — Inson-tarjimon tomonidan ko'rib chiqilgan, tarjimon imzosi va Ijrochi muhri mavjud tarjima; alohida tanlanadigan va to'lanadigan variant sifatida mavjud.", "• «Notarial tasdiq» — hamkor notarial jarayon mavjud bo'lgan joylarda sertifikatlangan tarjimon va/yoki hamkor notarius orqali tashkilashtirilgan qo'shimcha tasdiqlash jarayoni; avtomatik emas, alohida rasmiylashtiriladi.", "• «Platforma» — https://www.wpotranslations.org/ manzilida mavjud sayt va xizmatlar."] },
      { id: 'subject', heading: '3. Shartnoma predmeti', body: ["Ijrochi Buyurtmachi tanlagan xizmat darajasiga muvofiq hujjat tarjimasi xizmatlarini ko'rsatishga majburlanadi. Buyurtmachi ushbu xizmatlarni qabul qilish va Shartnoma shartlariga muvofiq to'lashga majburlanadi.", "Platforma ish jarayonida sun'iy intellekt yordamida qayta ishlashdan (OCR va mashina tarjimasi) foydalanadi. Inson-tarjimonning ishtiroki faqat aniq tanlangan va tasdiqlangan taqdirda ta'minlanadi."] },
      { id: 'service-levels', heading: '4. Xizmat darajalari', body: ["4.1 Elektron tarjima. Yuklangan hujjat AI yordamida tarjima qilinadi va PDF fayli shaklida yetkaziladi. Tarjimon imzosi, Ijrochi muhri yoki notarial tasdiq kiritilmaydi. Ma'lumot, ko'rib chiqish va tayyorlash maqsadida mo'ljallangan.", "4.2 Rasmiy tarjima (mavjud bo'lsa). Inson-tarjimon ko'rib chiqadi, tarjimon imzosi va Ijrochi muhri qo'yiladi. Buyurtma berish vaqtida aniq tanlanishi va Ijrochi tomonidan tasdiqlanishi kerak.", "4.3 Notarial tasdiq (mavjud bo'lsa). Ma'lum yurisdiksiyalarda sertifikatlangan tarjimon va/yoki hamkor notarius orqali tashkilashtiriladi. Avtomatik kiritilmaydi, alohida rasmiylashtiriladi."] },
      { id: 'order-process', heading: '5. Buyurtma berish tartibi', body: ["Buyurtma berish uchun: (1) ro'yxatdan o'tish yoki mavjud hisobdan foydalanish; (2) PDF formatida manba hujjatini yuklash; (3) til va hujjat turini tanlash; (4) xizmat darajasini tanlash; (5) buyurtmani tasdiqlash va to'lovni amalga oshirish."] },
      { id: 'customer-obligations', heading: '6. Buyurtmachining majburiyatlari', body: ["Buyurtmachi quyidagilarga rozilik bildiradi: • Faqat tarjima so'rashga haqqi bo'lgan hujjatlarni yuklash. • To'g'ri ma'lumot berish. • Xizmatdan firibgarlik yoki noqonuniy maqsadlarda foydalanmaslik. • Rasmiy maqsadlarda ishlatishdan oldin qabul qiluvchi tashkilot talablarini mustaqil ravishda tekshirish."] },
      { id: 'provider-obligations', heading: '7. Ijrochining majburiyatlari', body: ["Ijrochi tanlangan xizmat darajasiga muvofiq xizmat ko'rsatishga, hujjatni belgilangan muddatda yetkazishga, fayllarni Maxfiylik siyosatiga muvofiq xavfsiz saqlashga majburlanadi."] },
      { id: 'pricing', heading: '8. Narxlar', body: ["Xizmat narxi Ijrochi tomonidan belgilanadi va buyurtma vaqtida Platformada e'lon qilinadi. Ijrochi allaqachon to'langan buyurtmalarga ta'sir qilmasdan narxni o'zgartirish huquqini o'zida saqlaydi."] },
      { id: 'payment', heading: "9. To'lov shartlari", body: ["To'lov Ijrochi buyurtmani qayta ishlashni boshlamasdan oldin amalga oshirilishi kerak. Mavjud to'lov usullari to'lov vaqtida ko'rsatiladi."] },
      { id: 'fiscal', heading: '10. Fiskal cheklar', body: ["Amaldagi qonunchilik talab qilgan hollarda, Ijrochi fiskal cheklar yoki ekvivalent to'lov tasdiqlashlarini beradi."] },
      { id: 'cancellation', heading: '11. Bekor qilish va qaytarish qoidalari', body: ["11.1 Qayta ishlash boshlanmasidan oldin: Ijrochi hujjatni qayta ishlashni boshlamasidan oldin so'rov yuborilsa, to'liq qaytarish amalga oshiriladi.", "11.2 Qayta ishlash boshlanganidan keyin: Qayta ishlash (OCR, tarjima, PDF yaratish, tarjimon yoki notariusga topshirish) to'lov tasdiqlanganidan keyin avtomatik boshlanishi mumkin. Qayta ishlash boshlangandan so'ng buyurtmani bekor qilish mumkin bo'lmasligi mumkin. 11.3-bandda nazarda tutilgan hollar bundan mustasno, qaytarish amalga oshirilmaydi.", "11.3 Texnik xatolar: Ijrochi tomonidagi texnik xato tufayli hujjat yetkazilmasa yoki to'liq bo'lmasa, Ijrochi bepul qayta ishlashni amalga oshirishi mumkin. Qayta ishlash mumkin bo'lmasa, texnik xatoni bartaraf etmasa yoki Ijrochi aybi bilan hujjat yetkazilmasa — qaytarish amalga oshiriladi.", "11.4 Hujjat sifati past: Yuklangan fayl sifati past bo'lsa, qaytarish berilmaydi.", "11.5 Noto'g'ri ma'lumot: Buyurtmachining noto'g'ri kiritgan parametrlari uchun qaytarish berilmaydi.", "11.6 Qaytarish usuli: Tasdiqlangan qaytarishlar dastlabki to'lov usuli orqali 10 ish kuni ichida amalga oshiriladi."] },
      { id: 'ai-disclosure', heading: "12. Sun'iy intellekt yordamida qayta ishlash to'g'risida ma'lumot", body: ["Xizmat OCR va mashina tarjimasi uchun AI vositalaridan foydalanadi. AI tarjimalari xato bo'lishi mumkin. Elektron tarjima darajasi inson tomonidan ko'rib chiqishni o'z ichiga olmaydi."] },
      { id: 'translator', heading: '13. Tarjimon ishtiroki', body: ["Inson-tarjimonning ishtiroki faqat Rasmiy tarjima xizmat darajasida ta'minlanadi."] },
      { id: 'notarization', heading: '14. Hamkorlar orqali notarial tasdiq', body: ["Ijrochi ba'zi yurisdiksiyalarda notarial tasdiq taklif qilishi mumkin. Barcha buyurtmalar uchun kafolatlanmaydi."] },
      { id: 'no-guarantee', heading: '15. Uchinchi tomonlar tomonidan qabul qilinishi kafolatlanmaydi', body: ["Ijrochi tarjima hujjati elchixonalar, banklar, universitetlar yoki notariuslar tomonidan qabul qilinishini kafolatlamaydi. Buyurtmachi qabul qiluvchi tashkilot talablarini mustaqil ravishda tekshiradi."] },
      { id: 'liability', heading: '16. Javobgarlikni cheklash', body: ["Ijrochining umumiy javobgarligi muayyan buyurtma uchun to'langan miqdordan oshmaydi."] },
      { id: 'personal-data', heading: '17. Shaxsiy ma\'lumotlar', body: ["Ijrochi shaxsiy ma'lumotlarni https://www.wpotranslations.org/legal/privacy manzilida e'lon qilingan Maxfiylik siyosatiga muvofiq qayta ishlaydi."] },
      { id: 'storage', heading: '18. Hujjatlarni saqlash va o\'chirish', body: ["Fayllar tarjima yakunlanganidan 30 kun saqlangandan so'ng avtomatik ravishda butunlay o'chiriladi."] },
      { id: 'lang-priority', heading: '19. Til ustuvorligi', body: [LP] },
      { id: 'disputes', heading: '20. Nizolarni hal qilish', body: ["Har qanday nizo muzokaralar orqali hal qilinadi. Buyurtmachi worldprimeonline@gmail.com manziliga yozma da'vo yuboradi, Ijrochi 30 kalendar kun ichida javob beradi."] },
      { id: 'contact', heading: '21. Aloqa ma\'lumotlari', body: ['Ijrochi: IE WorldPrimeOnline', "Manzil: Olmaota sh.", 'Email: worldprimeonline@gmail.com', 'Sayt: https://www.wpotranslations.org/'] },
    ],
  },
  privacy: {
    slug: 'privacy',
    title: 'Maxfiylik siyosati',
    metaTitle: 'Maxfiylik siyosati — WPO Translations',
    metaDescription: "WPO Translations shaxsiy ma'lumotlarni qanday to'playdi, qayta ishlaydi, saqlaydi va himoya qiladi.",
    effectiveDate: '2026-05-26',
    sections: [
      { id: 'controller', heading: "1. Ma'lumotlar operatori", body: ["WorldPrimeOnline. Maxfiylik bo'yicha aloqa: worldprimeonline@gmail.com."] },
      { id: 'data-types', heading: "2. Qayta ishlanadigan shaxsiy ma'lumotlar turlari", body: ["• Hisob ma'lumotlari: elektron pochta manzili. • Yuklangan hujjatlar: tarjima uchun PDF fayllar. • Tarjima natijalari. • To'lov ma'lumotlari: tranzaksiya identifikatorlari va summalar. • Foydalanish ma'lumotlari."] },
      { id: 'purpose', heading: '3. Qayta ishlash maqsadlari', body: ["Tarjima xizmatini ko'rsatish, to'lovni qayta ishlash, hujjatlarni yetkazish, mijozlarni qo'llab-quvvatlash, xizmatni yaxshilash, qonuniy majburiyatlarni bajarish."] },
      { id: 'storage', heading: '4. Saqlash muddati (30 kun)', body: ["Fayllar tarjima yakunlanganidan 30 kun o'tgach avtomatik o'chiriladi. Hisob ma'lumotlari o'chirish so'rovigacha saqlanadi."] },
      { id: 'deletion', heading: "5. O'chirish so'rovi", body: ["Buyurtmachi hisob sozlamalari yoki worldprimeonline@gmail.com orqali fayllarni muddatidan oldin o'chirishni so'rashi mumkin."] },
      { id: 'third-parties', heading: '6. Uchinchi tomon protsessorlar', body: ["Supabase, Cloudflare R2, Mistral AI, Anthropic, Resend, Atlassian (Jira Cloud, rasmiy va notarial tarjima buyurtmalarini boshqarish), Sentry subprotsessorlardan foydalaniladi.", "• Rasmiy tarjima yoki Notarial tasdiq xizmat darajasi tanlangan taqdirda, tegishli hujjat ma'lumotlari buyurtmani bajarish uchun zarur bo'lgan darajada tayinlangan tarjimonlar, notariuslar va boshqa ishtirokchi hamkorlarga uzatilishi mumkin."] },
      { id: 'rights', heading: '7. Sizning huquqlaringiz', body: ["Kirish, to'g'rilash, o'chirish, e'tiroz bildirish va rozilikni qaytarib olish huquqlari mavjud. So'rov worldprimeonline@gmail.com manziliga yuboriladi."] },
      { id: 'lang-priority', heading: '8. Til ustuvorligi', body: [LP] },
      { id: 'contact', heading: '9. Aloqa', body: ['Ijrochi: IE WorldPrimeOnline', "Manzil: Olmaota sh.", 'Email: worldprimeonline@gmail.com', 'Sayt: https://www.wpotranslations.org/'] },
    ],
  },
  'personal-data-consent': {
    slug: 'personal-data-consent',
    title: "Shaxsiy ma'lumotlarni qayta ishlashga rozilik",
    metaTitle: "Shaxsiy ma'lumotlarga rozilik — WPO Translations",
    metaDescription: "WPO Translations xizmatlaridan foydalanishda shaxsiy ma'lumotlarni qayta ishlashga rozilik.",
    effectiveDate: '2026-05-26',
    sections: [
      { id: 'intro', heading: '1. Qo\'llanish doirasi', body: ["Ushbu hujjat Buyurtmachining WorldPrimeOnline Ijrochisiga https://www.wpotranslations.org/ tarjima xizmati bilan bog'liq shaxsiy ma'lumotlarni qayta ishlashga bergan roziligini tavsiflaydi."] },
      { id: 'what-data', heading: "2. Qayta ishlanadigan ma'lumotlar", body: ["• Elektron pochta manzili. • Yuklangan hujjatlar mazmuni. • Tarjima fayllari. • To'lov tranzaksiyalari ma'lumotlari. • Foydalanish metama'lumotlari."] },
      { id: 'purpose', heading: '3. Maqsadlar', body: ["Tarjima xizmatini ko'rsatish, to'lov, bildirishnomalar, mijozlarni qo'llab-quvvatlash, sifatni yaxshilash."] },
      { id: 'transfer', heading: "4. O'tkazish", body: ["Ma'lumotlar subprotsessorlarga va hamkorlarga (Rasmiy tarjima yoki Notarial tasdiq tanlanganda) o'tkazilishi mumkin."] },
      { id: 'retention', heading: '5. Saqlash', body: ["Fayllar tarjimadan 30 kun o'tgach o'chiriladi."] },
      { id: 'withdrawal', heading: '6. Rozilikni qaytarib olish', body: ["Buyurtmachi hisobni o'chirish yoki worldprimeonline@gmail.com orqali murojaat qilish yo'li bilan roziligini qaytarib olishi mumkin."] },
      { id: 'lang-priority', heading: '7. Til ustuvorligi', body: [LP] },
    ],
  },
  'refund-policy': {
    slug: 'refund-policy',
    title: 'Bekor qilish, qaytarish va qayta ishlash siyosati',
    metaTitle: 'Qaytarish siyosati — WPO Translations',
    metaDescription: 'WPO Translations qaytarish, bekor qilish va qayta ishlash qoidalari.',
    effectiveDate: '2026-05-26',
    sections: [
      { id: 'before-processing', heading: '1. Qayta ishlash boshlanmasidan oldin bekor qilish', body: ["Ijrochi qayta ishlashni boshlamasidan oldin so'rov yuborilsa, Buyurtmachi to'liq qaytarish oladi.", "Qayta ishlash to'lov tasdiqlanganidan keyin avtomatik boshlanishi mumkin. OCR, tarjima, PDF yaratish yoki tarjimon/notariusga topshirish boshlangandan so'ng bekor qilish mumkin bo'lmasligi mumkin."] },
      { id: 'after-processing', heading: '2. Qayta ishlash boshlanganidan keyin qaytarish yo\'q', body: ["Qayta ishlash boshlanganidan keyin 3-bo'limda nazarda tutilgan hollardan tashqari qaytarish amalga oshirilmaydi."] },
      { id: 'reprocessing', heading: '3. Texnik xatolar uchun qayta ishlash', body: ["Ijrochi tomonidagi texnik xato tufayli hujjat yetkazilmasa yoki to'liq bo'lmasa, Ijrochi bepul qayta ishlashni amalga oshirishi mumkin. Qayta ishlash mumkin bo'lmasa, texnik xatoni bartaraf etmasa yoki Ijrochi aybi bilan hujjat yetkazilmasa — qaytarish amalga oshiriladi."] },
      { id: 'poor-scan', heading: '4. Hujjat sifati past', body: ["Yuklangan fayl OCR uchun sifati past bo'lsa, qaytarish berilmaydi."] },
      { id: 'incorrect-input', heading: "5. Buyurtmachining noto'g'ri kiritgan ma'lumotlari", body: ["Ijrochi Buyurtmachining noto'g'ri parametrlari uchun javobgar emas."] },
      { id: 'partner-services', heading: '6. Rasmiy tarjima va notarial tasdiq', body: ["Tarjimon ishni boshlaganidan keyin Rasmiy tarjima to'lovi qaytarilmaydi."] },
      { id: 'method', heading: '7. Qaytarish usuli va muddati', body: ["Tasdiqlangan qaytarishlar dastlabki to'lov usuli orqali 10 ish kuni ichida amalga oshiriladi."] },
      { id: 'lang-priority', heading: '8. Til ustuvorligi', body: [LP] },
    ],
  },
  disclaimer: {
    slug: 'disclaimer',
    title: 'Tarjima maqomi bo\'yicha ogohlantirish',
    metaTitle: 'Ogohlantirish — WPO Translations',
    metaDescription: 'WPO Translations tarjimalarining maqomi va cheklovlari to\'g\'risida muhim ogohlantirish.',
    effectiveDate: '2026-05-26',
    sections: [
      { id: 'no-guarantee', heading: '1. Uchinchi tomonlar tomonidan qabul qilinishi kafolatlanmaydi', body: ["Banklar, universitetlar, konsulxonalar, migratsiya organlari va notariuslar tarjimani qabul qilishini kafolatlab bo'lmaydi."] },
      { id: 'no-advice', heading: '2. Yuridik maslahat berilmaydi', body: ["Platformadagi hech narsa yuridik, migratsiya, moliyaviy yoki notarial maslahat emas."] },
      { id: 'ai-limitations', heading: "3. Sun'iy intellekt qayta ishlashining cheklovlari", body: ["Mashina tarjimalari xato bo'lishi mumkin. Ijrochi to'liq aniqlikni kafolatlamaydi."] },
      { id: 'official-translation', heading: '4. Rasmiy tarjima', body: ["«Rasmiy tarjima» faqat inson-tarjimon ko'rib chiqqan va imzo qo'ygan xizmat darajasini bildiradi. Huquqiy ma'noda «tasdiqlangan tarjima» emas."] },
      { id: 'notarization', heading: '5. Notarial tasdiq', body: ["Notarial tasdiq faqat hamkorlik jarayoni mavjud bo'lgan joylarda va alohida rasmiylashtirilgan holda mavjud."] },
      { id: 'verify', heading: '6. Buyurtmachining javobgarligi', body: ["Buyurtmachi hujjatni tashkilotga topshirishdan oldin qabul qiluvchining talablarini mustaqil tekshirishi kerak."] },
      { id: 'lang-priority', heading: '7. Til ustuvorligi', body: [LP] },
    ],
  },
  terms: {
    slug: 'terms',
    title: 'Saytdan foydalanish shartlari',
    metaTitle: 'Foydalanish shartlari — WPO Translations',
    metaDescription: 'WPO Translations veb-sayt va platformasidan foydalanish shartlari.',
    effectiveDate: '2026-05-26',
    sections: [
      { id: 'acceptance', heading: '1. Shartlarni qabul qilish', body: ["https://www.wpotranslations.org/ platformasidan foydalanish ushbu Foydalanish shartlarini qabul qilishni bildiradi."] },
      { id: 'prohibited', heading: '2. Taqiqlangan harakatlar', body: ["• Tarjima so'rashga haqqi bo'lmagan hujjatlarni yuklash; • firibgarlik yoki noqonuniy maqsadlar; • teskari muhandislik; • ruxsatisiz avtomatlashtirilgan vositalar; • infratuzilmaga xalaqit berish."] },
      { id: 'ip', heading: '3. Intellektual mulk', body: ["Platformadagi barcha kontent Ijrochiga yoki uning litsenziya beruvchilariga tegishli. Buyurtmachi yuklangan hujjatlar ustidan mulk huquqini saqlab qoladi."] },
      { id: 'account', heading: '4. Hisob uchun javobgarlik', body: ["Buyurtmachi hisob ma'lumotlarining maxfiyligini saqlash uchun javobgar. Ruxsatsiz foydalanish aniqlanganda worldprimeonline@gmail.com ga xabar berishi kerak."] },
      { id: 'service-availability', heading: '5. Xizmat mavjudligi', body: ["Ijrochi platformaning mavjudligini ta'minlashga harakat qiladi, lekin uzluksiz kirishni kafolatlamaydi."] },
      { id: 'lang-priority', heading: '6. Til ustuvorligi', body: [LP] },
      { id: 'contact', heading: '7. Aloqa', body: ['Ijrochi: IE WorldPrimeOnline', "Manzil: Olmaota sh.", 'Email: worldprimeonline@gmail.com', 'Sayt: https://www.wpotranslations.org/'] },
    ],
  },
  partners: {
    slug: 'partners',
    title: 'Hamkorlar uchun shartlar',
    metaTitle: 'Hamkorlar — WPO Translations',
    metaDescription: "WPO Translations tarjimonlari, notariuslari, agentlari va referal hamkorlari uchun shartlar.",
    effectiveDate: '2026-05-26',
    sections: [
      { id: 'intro', heading: '1. Qo\'llanish doirasi', body: ["Ushbu Hamkorlar shartlari WorldPrimeOnline Ijrochisi bilan alohida hamkorlik shartnomasi tuzgan har qanday shaxs yoki tashkilotga qo'llaniladi."] },
      { id: 'no-employment', heading: '2. Mustaqil pudratchi maqomi', body: ["Hamkorlar Ijrochining xodimi emas — mustaqil pudratchilardir va shaxsiy soliq, sug'urta va qonunchilikka muvofiqlik uchun javobgardir."] },
      { id: 'translator-responsibility', heading: '3. Tarjimon va notariusning javobgarligi', body: ["Tarjimon imzo qo'ygan tarjimaning aniqligi, to'liqligi va kasbiy sifati uchun shaxsan javobgar."] },
      { id: 'commission', heading: '4. Referal mukofoti', body: ["Stavkalar alohida hamkorlik shartnomasida belgilanadi. alohida shartnomada belgilanadi."] },
      { id: 'confidentiality', heading: '5. Mijoz ma\'lumotlarining maxfiyligi', body: ["Hamkorlar mijoz hujjatlarini faqat shartnomaviy xizmat maqsadida ishlatadi."] },
      { id: 'no-misleading', heading: '6. Chalg\'ituvchi da\'volar taqiqi', body: ["Hamkorlar: tasdiqlangan bo'lmasa tarjimani sertifikatlangan deb e'lon qila olmaydi; qabul qilinishini kafolatlay olmaydi."] },
      { id: 'lang-priority', heading: '7. Til ustuvorligi', body: [LP] },
      { id: 'contact', heading: '8. Aloqa', body: ['Ijrochi: IE WorldPrimeOnline', "Manzil: Olmaota sh.", 'Email: worldprimeonline@gmail.com', 'Sayt: https://www.wpotranslations.org/'] },
    ],
  },
};
