import type { LegalDocs } from '../types';

const LP = '如本文件俄文版本与其他语言版本之间存在任何差异，除非提供方明确另有说明，以俄文版本为准。';

export const legalDocs: LegalDocs = {
  offer: {
    slug: 'offer',
    title: '公开要约协议',
    metaTitle: '公开要约 — WPO Translations',
    metaDescription: 'WPO Translations文件翻译服务公开要约协议。服务级别、定价、付款及退款条款。',
    effectiveDate: '2026-05-26',
    sections: [
      { id: 'provider', heading: '1. 服务提供方信息', body: ['本公开要约协议（以下简称"协议"）由WorldPrimeOnline发布，（以下简称"服务商"）。', '联系方式：worldprimeonline@gmail.com', '网站：https://www.wpotranslations.org/', '地址：阿拉木图，卡济别克比大街139/1', '发布日期：2026-05-26', '本协议构成适用法律下的公开要约。在平台上下订单即表示接受本协议的全部条款。'] },
      { id: 'definitions', heading: '2. 定义', body: ['• "客户" — 通过平台下订单的任何个人或法律实体。', '• "服务" — 服务商提供的文件翻译服务。', '• "电子翻译" — 以电子格式提供的翻译，不含译员签名、服务商印章或公证，除非客户另行选择。', '• "官方翻译" — 经人工译员审核、含译员签名和服务商印章的翻译，需单独选择并付费。', '• "公证" — 在有合作公证流程的地区，通过认证译员和/或合作公证人安排的额外认证程序，不自动包含，需单独办理。', '• "平台" — https://www.wpotranslations.org/上可访问的网站及服务。'] },
      { id: 'subject', heading: '3. 协议标的', body: ['服务商同意按客户选择的服务级别提供文件翻译服务。客户同意按本协议条款接受并支付此类服务费用。', '平台在工作流程中使用人工智能辅助处理（光学字符识别和机器翻译）。只有在明确选择并确认的情况下，才会有人工译员参与。'] },
      { id: 'service-levels', heading: '4. 服务级别', body: ['4.1 电子翻译：服务商使用AI辅助OCR和机器翻译工具翻译上传的文件，以PDF格式交付。不含译员签名、服务商印章或公证。供参考、审阅和准备用途。', '4.2 官方翻译（如有）：由人工译员审核翻译内容，输出文件含译员签名和服务商印章。需在下订单时明确选择并由服务商确认。', '4.3 公证（如有）：在特定司法管辖区通过认证译员和/或合作公证人安排的额外认证程序。不自动提供，需单独安排，取决于合作方的可用性。'] },
      { id: 'order-process', heading: '5. 订单流程', body: ['下订单须：(1) 注册或使用现有账户；(2) 上传PDF格式源文件；(3) 选择源语言、目标语言和文件类型；(4) 选择所需服务级别；(5) 确认订单并完成付款。', '订单在收到付款确认后视为服务商接受。如上传文件不符合质量要求，服务商有权拒绝订单。'] },
      { id: 'customer-obligations', heading: '6. 客户义务', body: ['客户同意：', '• 仅上传其有权申请翻译的文件。', '• 提供准确的文件类型、语言和用途信息。', '• 不将服务用于欺诈、欺骗或非法目的。', '• 在将翻译文件用于正式用途前，自行向接收机构核实其要求。', '• 不因任何第三方拒绝接受翻译文件而追究服务商责任。'] },
      { id: 'provider-obligations', heading: '7. 服务商义务', body: ['服务商同意：按选定服务级别提供服务；在平台规定时间内交付翻译文件；确保上传文件的安全存储；仅为隐私政策规定的目的处理个人数据；就本协议条款的重大变更通知客户。'] },
      { id: 'pricing', heading: '8. 定价', body: ['服务费用由服务商确定，在下订单时在平台上公布。服务商保留在不影响已付款订单的情况下更改价格的权利。', '电子翻译的价格取决于客户选择的文件类型。官方翻译和公证需额外收费。'] },
      { id: 'payment', heading: '9. 付款条款', body: ['付款须在服务商开始处理订单前完成。可用付款方式在结账时显示。', '服务商使用第三方支付处理服务。完成付款即表示接受相关支付服务商的条款。'] },
      { id: 'fiscal', heading: '10. 财务收据', body: ['在适用法律要求的情况下，服务商为已完成的付款提供财务收据或等效付款确认。', '客户可通过平台账户或联系worldprimeonline@gmail.com请求付款确认副本。'] },
      { id: 'cancellation', heading: '11. 取消和退款规则', body: ['11.1 处理开始前：如在服务商开始处理前提出取消请求，客户可获得全额退款。', '11.2 处理开始后：处理开始后不予退款，除非因服务商技术故障导致翻译文件无法交付。', '11.3 技术错误：如因服务商技术错误导致翻译文件明显不完整或损坏，客户有权免费重新处理或全额退款。', '11.4 文件质量差：如源文件模糊、损坏或扫描质量不足，不提供退款。', '11.5 客户输入错误：如因客户输入参数错误导致翻译结果有误，不提供退款。', '11.6 退款方式：经批准的退款通过原始付款方式处理，批准后10个工作日内完成。'] },
      { id: 'ai-disclosure', heading: '12. AI辅助处理披露', body: ['服务使用AI工具进行光学字符识别（OCR）和机器翻译。AI生成的翻译可能包含错误、遗漏或不准确之处。', '电子翻译级别不含人工审核。需要人工审核的客户应选择官方翻译级别（如有）。', '服务商不保证翻译输出无误，也不保证符合任何特定机构的要求。'] },
      { id: 'translator', heading: '13. 译员参与', body: ['只有在官方翻译服务级别才有人工译员参与。在该级别，合格译员审核AI生成的翻译，在必要时进行更正，并在文件上签名并加盖服务商印章。'] },
      { id: 'notarization', heading: '14. 通过合作方公证', body: ['服务商可在特定司法管辖区通过认证译员和公证人合作方提供公证服务。不适用于所有文件类型、语言组合或地区。', '公证需单独安排，取决于合作方的可用性，可能需要额外费用。服务商不保证每个订单都能提供公证。'] },
      { id: 'no-guarantee', heading: '15. 不保证第三方接受', body: ['服务商不保证翻译文件会被任何大使馆、领事馆、移民机构、银行、大学、公证人、法院或其他机构接受。', '不同机构和司法管辖区对翻译格式、认证级别和文件呈现方式的要求各不相同。客户须自行核实接收方的要求。'] },
      { id: 'liability', heading: '16. 责任限制', body: ['在适用法律允许的最大范围内，服务商对任何索赔的总责任不超过客户为引发该索赔的具体订单支付的金额。', '服务商不对任何间接、附带、后果性或特殊损害承担责任。'] },
      { id: 'personal-data', heading: '17. 个人数据', body: ['服务商按照发布于https://www.wpotranslations.org/legal/privacy的隐私政策处理客户个人数据。'] },
      { id: 'storage', heading: '18. 文件存储与删除', body: ['上传文件和翻译文件在翻译完成后最多存储30天，30天后自动永久删除。客户可通过账户设置或联系worldprimeonline@gmail.com申请提前删除。'] },
      { id: 'lang-priority', heading: '19. 语言优先级', body: [LP] },
      { id: 'disputes', heading: '20. 争议解决', body: ['因本协议引起的任何争议，应先进行诉前解决。客户应向worldprimeonline@gmail.com提交书面索赔，服务商应在30个日历日内答复。', '如争议无法友好解决，应提交服务商注册地址的有管辖权法院，依据适用法律处理。'] },
      { id: 'contact', heading: '21. 联系方式', body: ['服务商：IE WorldPrimeOnline', '地址：阿拉木图，卡济别克比大街139/1', 'Email：worldprimeonline@gmail.com', '网站：https://www.wpotranslations.org/'] },
    ],
  },
  privacy: {
    slug: 'privacy',
    title: '隐私政策',
    metaTitle: '隐私政策 — WPO Translations',
    metaDescription: 'WPO Translations如何收集、处理、存储和保护您的个人数据。数据保留、删除和您的权利。',
    effectiveDate: '2026-05-26',
    sections: [
      { id: 'controller', heading: '1. 数据控制者', body: ['本隐私政策由WorldPrimeOnline（WorldPrimeOnline）（以下简称"服务商"）发布。隐私事务联系：worldprimeonline@gmail.com。'] },
      { id: 'data-types', heading: '2. 处理的个人数据类型', body: ['服务商处理以下类别的个人数据：', '• 账户信息：注册时提供的电子邮件地址。', '• 上传文件：提交翻译的PDF文件，可能含姓名、出生日期、证件号码、地址、财务数据等个人信息。', '• 翻译输出文件。', '• 支付数据：交易标识符和金额（不存储支付卡号或密钥）。', '• 使用数据：时间戳、文件类型、语言对、技术日志。'] },
      { id: 'purpose', heading: '3. 处理目的', body: ['个人数据仅用于以下目的：提供翻译服务；处理和验证付款；交付翻译文件和通知；响应客服请求；改善服务；遵守法律义务。'] },
      { id: 'legal-basis', heading: '4. 处理的法律依据', body: ['处理基于客户同意（在注册和下订单时提供）、履行客户与服务商之间的合同，以及服务商在运营和改善服务方面的合法利益。'] },
      { id: 'storage', heading: '5. 存储期限与30天文件保留', body: ['上传源文件和翻译文件在翻译完成30天后自动永久删除。账户信息保留至客户删除账户。付款记录按适用财务和税务法规保留。'] },
      { id: 'deletion', heading: '6. 删除请求', body: ['客户可通过账户设置或联系worldprimeonline@gmail.com申请在30天保留期届满前删除上传文件。账户删除请求将导致与账户相关的所有个人数据被永久删除。'] },
      { id: 'third-parties', heading: '7. 第三方处理方', body: ['服务商使用以下子处理方：Supabase（数据库和认证）、Cloudflare R2（加密文件存储）、Mistral AI（OCR）、Anthropic（AI翻译）、Resend（邮件通知）、Sentry（错误监控，仅匿名技术数据）。所有子处理方均禁止将客户数据用于合同服务以外的目的。'] },
      { id: 'security', heading: '8. 安全措施', body: ['上传文件和翻译文件以加密方式静态存储，传输数据受TLS保护，文件访问权限限于经认证的客户账户。'] },
      { id: 'cross-border', heading: '9. 跨境数据传输', body: ['部分子处理方可能在客户居住国以外处理数据。在此情况下，服务商确保按适用数据保护法律建立适当保障措施。'] },
      { id: 'rights', heading: '10. 您的权利', body: ['依据适用法律，客户有权：访问个人数据；更正不准确数据；请求删除数据；在特定情况下反对或限制处理；随时撤回同意。请联系worldprimeonline@gmail.com行使权利，请求将在30个日历日内处理。'] },
      { id: 'cookies', heading: '11. Cookie', body: ['服务商仅使用认证所需的必要Cookie（由Supabase管理）和语言偏好Cookie（NEXT_LOCALE）。不使用广告或跟踪Cookie。'] },
      { id: 'changes', heading: '12. 政策变更', body: ['服务商可能更新本隐私政策，重大变更将通过电子邮件或平台通知告知。继续使用服务即表示接受更新后的政策。'] },
      { id: 'lang-priority', heading: '13. 语言优先级', body: [LP] },
      { id: 'contact', heading: '14. 联系方式', body: ['服务商：IE WorldPrimeOnline', '地址：阿拉木图，卡济别克比大街139/1', '联系方式：worldprimeonline@gmail.com', '网站：https://www.wpotranslations.org/'] },
    ],
  },
  'personal-data-consent': {
    slug: 'personal-data-consent',
    title: '个人数据处理同意书',
    metaTitle: '个人数据同意书 — WPO Translations',
    metaDescription: '使用WPO Translations服务时的个人数据处理同意书。',
    effectiveDate: '2026-05-26',
    sections: [
      { id: 'intro', heading: '1. 适用范围', body: ['本文件包含客户向WorldPrimeOnline（WorldPrimeOnline）（"服务商"）就使用https://www.wpotranslations.org/文件翻译服务所提供的个人数据处理同意。'] },
      { id: 'what-data', heading: '2. 处理的个人数据', body: ['使用本服务，客户同意处理：', '• 注册时提供的电子邮件地址。', '• 上传文件的内容（可能含姓名、出生日期、证件号码、地址、国籍、银行账户详情、就业信息、医疗数据等）。', '• 含上述数据的目标语言翻译文件。', '• 支付交易数据（标识符和金额，不存储支付凭证）。', '• 使用元数据（时间戳、文件类型、语言对）。'] },
      { id: 'purpose', heading: '3. 处理目的', body: ['个人数据处理目的：提供请求的翻译服务；处理和验证付款；交付翻译文件和通知；客户支持；改善服务质量；遵守法律义务。'] },
      { id: 'transfer', heading: '4. 向处理方和合作方转移', body: ['服务商可将个人数据转移给第三方处理方（Supabase、Cloudflare R2、Mistral AI、Anthropic、Resend），仅用于提供服务。选择官方翻译或公证级别时，相关文件数据可能与指定译员或公证人合作方共享。'] },
      { id: 'retention', heading: '5. 保留与删除', body: ['上传源文件和翻译文件在翻译完成30天后自动永久删除。账户数据保留至申请删除账户时。客户可随时通过账户设置或联系worldprimeonline@gmail.com申请提前删除。'] },
      { id: 'withdrawal', heading: '6. 撤回同意', body: ['客户可随时通过删除账户或联系worldprimeonline@gmail.com撤回同意。撤回同意不影响撤回前处理的合法性。撤回同意可能导致某些服务功能无法使用。'] },
      { id: 'lang-priority', heading: '7. 语言优先级', body: [LP] },
    ],
  },
  'refund-policy': {
    slug: 'refund-policy',
    title: '取消、退款和重新处理政策',
    metaTitle: '退款政策 — WPO Translations',
    metaDescription: 'WPO Translations退款、取消和重新处理规则。',
    effectiveDate: '2026-05-26',
    sections: [
      { id: 'before-processing', heading: '1. 处理开始前取消', body: ['如在服务商开始处理上传文件前提出取消请求，客户可获得全额退款。请尽快联系worldprimeonline@gmail.com取消订单。'] },
      { id: 'after-processing', heading: '2. 处理开始后不予退款', body: ['处理开始后（OCR提取、翻译或PDF生成），不予退款，除非：', '• 因服务商技术故障导致翻译文件无法交付。', '• 输出因系统错误明显不完整。', '源文件清晰且订单参数正确输入的情况下，对翻译质量、风格或术语的不满不构成退款理由。'] },
      { id: 'reprocessing', heading: '3. 技术错误的重新处理', body: ['如因服务商技术错误导致翻译文件明显不完整或严重损坏，客户有权免费重新处理。重新处理请求须在文件交付后7天内联系worldprimeonline@gmail.com提出，并附上问题描述和订单参考号。'] },
      { id: 'poor-scan', heading: '4. 文件或文件质量差', body: ['如上传文件质量不足以准确提取文本（模糊扫描、水印重、手写内容等），不自动提供退款或重新处理。建议客户在订购前检查文件质量。'] },
      { id: 'incorrect-input', heading: '5. 客户输入错误', body: ['服务商不对客户错误输入参数（语言、文件类型）导致的翻译错误负责，此情况不予退款。'] },
      { id: 'partner-services', heading: '6. 官方翻译和公证退款', body: ['指定译员开始工作后，官方翻译费用不予退款。公证费用受合作译员或公证人条款约束，程序开始后通常不予退款。'] },
      { id: 'method', heading: '7. 退款方式和时限', body: ['经批准的退款通过原始付款方式处理，批准后通常10个工作日内完成。请联系worldprimeonline@gmail.com并提供订单参考号申请退款。'] },
      { id: 'lang-priority', heading: '8. 语言优先级', body: [LP] },
    ],
  },
  disclaimer: {
    slug: 'disclaimer',
    title: '翻译状态免责声明',
    metaTitle: '免责声明 — WPO Translations',
    metaDescription: 'WPO Translations翻译状态和限制的重要免责声明。',
    effectiveDate: '2026-05-26',
    sections: [
      { id: 'no-guarantee', heading: '1. 不保证第三方接受', body: ['第三方（包括银行、大学、领事馆、移民机构和公证人）是否接受翻译不予保证，取决于相关机构的要求。每个机构和司法管辖区可能对翻译格式、认证级别和文件呈现有不同要求。客户须自行核实。'] },
      { id: 'no-advice', heading: '2. 不提供法律、移民或专业建议', body: ['平台上的任何内容和翻译文件均不构成法律、移民、财务、医疗或公证建议。服务商不就翻译是否被任何特定申请或程序接受提供建议。'] },
      { id: 'ai-limitations', heading: '3. AI辅助处理的局限性', body: ['电子翻译服务级别使用基于AI的OCR和机器翻译。这些系统可能产生错误、遗漏或不准确，尤其在复杂排版、专业术语、手写内容或低质量扫描方面。服务商不保证AI生成翻译无误。'] },
      { id: 'official-translation', heading: '4. 官方翻译', body: ['本条款中的"官方翻译"仅指人工译员审核输出并附上签名和服务商印章的服务级别。除非服务商就特定司法管辖区和用途以书面形式明确确认，否则不构成法律意义上的"认证翻译"。'] },
      { id: 'notarization', heading: '5. 公证', body: ['公证仅在存在合作流程的情况下提供，并需单独安排。不保证适用于所有文件类型、语言对或司法管辖区。'] },
      { id: 'verify', heading: '6. 客户核实要求的责任', body: ['在向任何机构提交翻译文件前，客户须自行核实格式、认证级别和内容是否符合接收方要求。服务商不对因客户未核实要求而使用翻译文件导致的不利后果承担责任。'] },
      { id: 'lang-priority', heading: '7. 语言优先级', body: [LP] },
    ],
  },
  terms: {
    slug: 'terms',
    title: '网站使用条款',
    metaTitle: '使用条款 — WPO Translations',
    metaDescription: 'WPO Translations网站和平台使用条款。',
    effectiveDate: '2026-05-26',
    sections: [
      { id: 'acceptance', heading: '1. 接受条款', body: ['访问或使用https://www.wpotranslations.org/平台即表示您同意遵守本网站使用条款。本条款适用于所有访客、注册用户和客户。'] },
      { id: 'website-use', heading: '2. 许可使用', body: ['平台可用于按公开要约协议获取文件翻译服务，以及为个人或商业文件翻译需求浏览和使用平台功能。'] },
      { id: 'prohibited', heading: '3. 禁止活动', body: ['用户不得：', '• 上传无权申请翻译的文件。', '• 将平台用于欺诈、欺骗或非法目的。', '• 上传含违禁内容的文件。', '• 尝试对服务商软件、模型或专有方法进行逆向工程、反编译或提取。', '• 未经服务商事先书面授权，使用自动化工具、机器人或脚本访问平台。', '• 干扰或破坏平台基础设施、系统或服务。', '• 尝试未经授权访问其他用户的账户或数据。'] },
      { id: 'ip', heading: '4. 知识产权', body: ['平台上的所有内容，包括软件、设计、文字、徽标和翻译方法，均为服务商或其许可方的财产，受适用知识产权法保护。', '客户保留对其上传源文件的所有权。服务商不主张对客户文件的所有权。'] },
      { id: 'account', heading: '5. 账户责任', body: ['客户负责维护账户凭证的保密性，并对账户下发生的所有活动负责。如发现账户被未经授权使用，应立即通知worldprimeonline@gmail.com。'] },
      { id: 'service-availability', heading: '6. 服务可用性', body: ['服务商尽力维持平台可用性，但不保证不间断、无错误的访问。平台可能因维护、更新或不可控情况而暂时不可用。'] },
      { id: 'changes', heading: '7. 条款变更', body: ['服务商可随时更新本条款。继续使用平台即表示接受更新后的条款。重大变更将通过电子邮件或平台通知告知。'] },
      { id: 'lang-priority', heading: '8. 语言优先级', body: [LP] },
      { id: 'contact', heading: '9. 联系方式', body: ['服务商：IE WorldPrimeOnline', '地址：阿拉木图，卡济别克比大街139/1', '联系方式：worldprimeonline@gmail.com', '网站：https://www.wpotranslations.org/'] },
    ],
  },
  partners: {
    slug: 'partners',
    title: '合作伙伴条款',
    metaTitle: '合作伙伴 — WPO Translations',
    metaDescription: 'WPO Translations译员、公证人、代理人和推荐合作伙伴条款。',
    effectiveDate: '2026-05-26',
    sections: [
      { id: 'intro', heading: '1. 适用范围和合作伙伴定义', body: ['本合作伙伴条款适用于与WorldPrimeOnline（WorldPrimeOnline）（"服务商"）签订单独合作协议的任何个人或实体。"合作伙伴"包括认证译员、公证人、推荐代理人、移民顾问、教育顾问及其他服务提供商。'] },
      { id: 'no-employment', heading: '2. 独立承包商身份', body: ['合作伙伴是独立承包商，不是服务商的雇员、代理人或法定代表人。合作伙伴自行负责纳税、专业费用、保险及遵守适用法律。'] },
      { id: 'translator-responsibility', heading: '3. 译员和公证人责任', body: ['提供官方翻译的译员须持有其司法管辖区认可的专业资质，并对签名的翻译的准确性、完整性和专业质量负责。', '提供认证服务的公证人须确保其行为符合适用公证法律和专业标准。', '服务商对合作伙伴提供的服务的责任在适用法律允许的范围内受到限制。'] },
      { id: 'commission', heading: '4. 推荐佣金和商业条款', body: ['推荐佣金比率和商业条款在合作伙伴与服务商签订的个人合作协议中规定。', '佣金条款：[佣金率/推荐条款占位符 — 在个人协议中确定]。'] },
      { id: 'confidentiality', heading: '5. 客户数据保密', body: ['通过平台接收客户文件的合作伙伴须遵守严格的保密义务，不得披露、过期保留或将客户文件和个人数据用于合同服务以外的目的。'] },
      { id: 'no-misleading', heading: '6. 禁止误导性陈述', body: ['合作伙伴不得：夸大翻译的性质、状态或范围；将电子翻译声称为认证或公证翻译（除非属实）；保证翻译文件被任何机构接受；未经书面授权声称代表服务商。'] },
      { id: 'termination', heading: '7. 合作终止', body: ['任何一方均可按个人合作协议的通知规定终止合作关系。如合作伙伴违反本条款、从事欺诈活动或损害客户，服务商保留立即暂停或终止其平台访问权限的权利。'] },
      { id: 'lang-priority', heading: '8. 语言优先级', body: [LP] },
      { id: 'contact', heading: '9. 合作咨询联系方式', body: ['服务商：IE WorldPrimeOnline', '地址：阿拉木图，卡济别克比大街139/1', '联系方式：worldprimeonline@gmail.com', '网站：https://www.wpotranslations.org/'] },
    ],
  },
};
