// Auto-generated by: supabase gen types --project-id qziwyakewuneokzdpoyf --schema public
// Re-run after schema changes: supabase gen types --project-id qziwyakewuneokzdpoyf --schema public > src/types/supabase.ts
// Requires: supabase login --token <YOUR_PAT>
//
// Manually maintained to match the current target schema (see supabase/STAGING_INIT_ALL.sql).
// Tables: users, documents, jobs, ocr_results, translations, payment_transactions, subscriptions,
//         job_audit_log, staff_profiles, notification_log, fiscal_receipts, refund_transactions
// Excluded: payments (dead Stripe-era table), ton_payments (renamed), wallet_links (dropped)

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          created_at: string;
          terms_accepted_at: string | null;
        };
        Insert: {
          id: string;
          email: string;
          created_at?: string;
          terms_accepted_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          created_at?: string;
          terms_accepted_at?: string | null;
        };
        Relationships: [];
      };
      documents: {
        Row: {
          id: string;
          user_id: string;
          filename: string;
          original_file_size: number;
          file_key: string;
          source_language: string;
          target_language: string;
          document_type: string;
          status: 'uploading' | 'processing' | 'completed' | 'failed';
          detected_source_language: string | null;
          /** Client IP at upload time — fraud prevention and dispute/chargeback handling only */
          ip_address: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          filename: string;
          original_file_size: number;
          file_key: string;
          source_language: string;
          target_language: string;
          document_type: string;
          status: 'uploading' | 'processing' | 'completed' | 'failed';
          detected_source_language?: string | null;
          ip_address?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          filename?: string;
          original_file_size?: number;
          file_key?: string;
          source_language?: string;
          target_language?: string;
          document_type?: string;
          status?: 'uploading' | 'processing' | 'completed' | 'failed';
          detected_source_language?: string | null;
          ip_address?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: 'documents_user_id_fkey'; columns: ['user_id']; referencedRelation: 'users'; referencedColumns: ['id'] },
        ];
      };
      jobs: {
        Row: {
          id: string;
          document_id: string;
          status: 'payment_pending' | 'queued' | 'ocr_in_progress' | 'ocr_completed' | 'translation_in_progress' | 'pdf_rendering' | 'completed' | 'failed';
          error_message: string | null;
          progress_percent: number;
          priority: number;
          payment_source: 'card_payment' | 'subscription' | null;
          /** Price in KZT (whole tenge). Set at creation for card payment orders. */
          price_kzt: number | null;
          /** @deprecated Use service_level instead. Kept for backward compat. */
          notarized: boolean;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
          /** Workflow status for official translation pipeline. Default: 'completed' for pre-migration rows. */
          workflow_status: string | null;
          /** Primary service level field. Supersedes notarized boolean. */
          service_level: 'electronic' | 'official_with_translator_signature_and_provider_stamp' | 'notarization_through_partners' | null;
          notary_city: string | null;
          fulfillment_method: 'pickup' | 'delivery' | null;
          /** Stored server-side only. Never synced to Jira/Telegram. */
          delivery_phone: string | null;
          /** Stored server-side only. Never synced to Jira/Telegram. */
          delivery_address: string | null;
          jira_issue_id: string | null;
          jira_issue_key: string | null;
          jira_issue_url: string | null;
          google_drive_folder_id: string | null;
          google_drive_folder_url: string | null;
          jira_sync_status: string | null;
          drive_sync_status: string | null;
          last_integration_error: string | null;
          last_synced_at: string | null;
        };
        Insert: {
          id?: string;
          document_id: string;
          status: 'payment_pending' | 'queued' | 'ocr_in_progress' | 'ocr_completed' | 'translation_in_progress' | 'pdf_rendering' | 'completed' | 'failed';
          error_message?: string | null;
          progress_percent?: number;
          priority?: number;
          payment_source?: 'card_payment' | 'subscription' | null;
          price_kzt?: number | null;
          notarized?: boolean;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          workflow_status?: string | null;
          service_level?: 'electronic' | 'official_with_translator_signature_and_provider_stamp' | 'notarization_through_partners' | null;
          notary_city?: string | null;
          fulfillment_method?: 'pickup' | 'delivery' | null;
          delivery_phone?: string | null;
          delivery_address?: string | null;
          jira_issue_id?: string | null;
          jira_issue_key?: string | null;
          jira_issue_url?: string | null;
          google_drive_folder_id?: string | null;
          google_drive_folder_url?: string | null;
          jira_sync_status?: string | null;
          drive_sync_status?: string | null;
          last_integration_error?: string | null;
          last_synced_at?: string | null;
        };
        Update: {
          id?: string;
          document_id?: string;
          status?: 'payment_pending' | 'queued' | 'ocr_in_progress' | 'ocr_completed' | 'translation_in_progress' | 'pdf_rendering' | 'completed' | 'failed';
          error_message?: string | null;
          progress_percent?: number;
          priority?: number;
          payment_source?: 'card_payment' | 'subscription' | null;
          notarized?: boolean;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          workflow_status?: string | null;
          service_level?: 'electronic' | 'official_with_translator_signature_and_provider_stamp' | 'notarization_through_partners' | null;
          notary_city?: string | null;
          fulfillment_method?: 'pickup' | 'delivery' | null;
          delivery_phone?: string | null;
          delivery_address?: string | null;
          jira_issue_id?: string | null;
          jira_issue_key?: string | null;
          jira_issue_url?: string | null;
          google_drive_folder_id?: string | null;
          google_drive_folder_url?: string | null;
          jira_sync_status?: string | null;
          drive_sync_status?: string | null;
          last_integration_error?: string | null;
          last_synced_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'jobs_document_id_fkey'; columns: ['document_id']; referencedRelation: 'documents'; referencedColumns: ['id'] },
        ];
      };
      job_audit_log: {
        Row: {
          id: string;
          job_id: string;
          actor: string;
          source: string;
          action: string;
          previous_status: string | null;
          new_status: string | null;
          jira_issue_key: string | null;
          correlation_id: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          actor: string;
          source: string;
          action: string;
          previous_status?: string | null;
          new_status?: string | null;
          jira_issue_key?: string | null;
          correlation_id?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: Record<string, never>;
        Relationships: [
          { foreignKeyName: 'job_audit_log_job_id_fkey'; columns: ['job_id']; referencedRelation: 'jobs'; referencedColumns: ['id'] },
        ];
      };
      ocr_results: {
        Row: {
          id: string;
          job_id: string;
          markdown: string;
          page_count: number;
          detected_language: string | null;
          provider: 'mistral' | 'google_docai';
          created_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          markdown: string;
          page_count: number;
          detected_language?: string | null;
          provider: 'mistral' | 'google_docai';
          created_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          markdown?: string;
          page_count?: number;
          detected_language?: string | null;
          provider?: 'mistral' | 'google_docai';
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: 'ocr_results_job_id_fkey'; columns: ['job_id']; referencedRelation: 'jobs'; referencedColumns: ['id'] },
        ];
      };
      translations: {
        Row: {
          id: string;
          job_id: string;
          translated_markdown: string;
          translated_pdf_key: string;
          /** Key for translator review DOCX draft. Added by add_official_workflow_fields.sql migration. */
          translated_docx_key: string | null;
          /** Key for preview PDF generated before human review. Added by add_official_workflow_fields.sql migration. */
          translated_preview_pdf_key: string | null;
          /** QA report stored as JSONB. Added by add_official_workflow_fields.sql migration. */
          qa_report: Json | null;
          /** Structured translation AST (TranslationDocumentAst). Added by 0014_add_translated_ast.sql. Null for legacy jobs. */
          translated_ast: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          translated_markdown: string;
          translated_pdf_key: string;
          translated_docx_key?: string | null;
          translated_preview_pdf_key?: string | null;
          qa_report?: Json | null;
          translated_ast?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          translated_markdown?: string;
          translated_pdf_key?: string;
          translated_docx_key?: string | null;
          translated_preview_pdf_key?: string | null;
          qa_report?: Json | null;
          translated_ast?: Json | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: 'translations_job_id_fkey'; columns: ['job_id']; referencedRelation: 'jobs'; referencedColumns: ['id'] },
        ];
      };
      payment_transactions: {
        Row: {
          id: string;
          user_id: string;
          document_id: string;
          job_id: string;
          amount: number;
          currency: string;
          payment_provider: string;
          payment_source: string | null;
          status:
            | 'pending' | 'completed' | 'expired'           // legacy TON-era
            | 'payment_pending' | 'paid' | 'failed' | 'canceled'
            | 'refund_pending' | 'refunded' | 'requires_review' | 'duplicate_charge_review';
          provider_transaction_id: string | null;
          provider_invoice_id: string | null;
          provider_invoice_suffix6: string | null;
          provider_status: string | null;
          provider_reason: string | null;
          provider_reason_code: string | null;
          secret_hash_digest: string | null;
          attempt_number: number;
          card_mask: string | null;
          card_type: string | null;
          issuer: string | null;
          approval_code: string | null;
          reference: string | null;
          secure: string | null;
          provider_environment: 'test' | 'production';
          raw_payload: Json | null;
          provider_payload: Json | null;
          ip_address: string | null;
          callback_received_at: string | null;
          status_checked_at: string | null;
          paid_at: string | null;
          failed_at: string | null;
          refunded_at: string | null;
          expires_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          document_id: string;
          job_id: string;
          amount: number;
          currency?: string;
          payment_provider?: string;
          payment_source?: string | null;
          status?: string;
          provider_transaction_id?: string | null;
          provider_invoice_id?: string | null;
          provider_invoice_suffix6?: string | null;
          provider_status?: string | null;
          provider_reason?: string | null;
          provider_reason_code?: string | null;
          secret_hash_digest?: string | null;
          attempt_number?: number;
          card_mask?: string | null;
          card_type?: string | null;
          issuer?: string | null;
          approval_code?: string | null;
          reference?: string | null;
          secure?: string | null;
          provider_environment?: 'test' | 'production';
          raw_payload?: Json | null;
          provider_payload?: Json | null;
          ip_address?: string | null;
          callback_received_at?: string | null;
          status_checked_at?: string | null;
          paid_at?: string | null;
          failed_at?: string | null;
          refunded_at?: string | null;
          expires_at: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: string;
          provider_transaction_id?: string | null;
          provider_status?: string | null;
          provider_reason?: string | null;
          provider_reason_code?: string | null;
          card_mask?: string | null;
          card_type?: string | null;
          issuer?: string | null;
          approval_code?: string | null;
          reference?: string | null;
          secure?: string | null;
          raw_payload?: Json | null;
          provider_payload?: Json | null;
          ip_address?: string | null;
          callback_received_at?: string | null;
          status_checked_at?: string | null;
          paid_at?: string | null;
          failed_at?: string | null;
          refunded_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: 'payment_transactions_user_id_fkey'; columns: ['user_id']; referencedRelation: 'users'; referencedColumns: ['id'] },
          { foreignKeyName: 'payment_transactions_document_id_fkey'; columns: ['document_id']; referencedRelation: 'documents'; referencedColumns: ['id'] },
          { foreignKeyName: 'payment_transactions_job_id_fkey'; columns: ['job_id']; referencedRelation: 'jobs'; referencedColumns: ['id'] },
        ];
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          plan: 'basic' | 'pro';
          status: 'pending' | 'active' | 'expired' | 'cancelled';
          documents_limit: number;
          documents_used: number;
          amount: number | null;
          provider_transaction_id: string | null;
          started_at: string | null;
          expires_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          plan: 'basic' | 'pro';
          status?: 'pending' | 'active' | 'expired' | 'cancelled';
          documents_limit: number;
          documents_used?: number;
          amount?: number | null;
          provider_transaction_id?: string | null;
          started_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
        };
        Update: {
          status?: 'pending' | 'active' | 'expired' | 'cancelled';
          documents_used?: number;
          provider_transaction_id?: string | null;
          started_at?: string | null;
          expires_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'subscriptions_user_id_fkey'; columns: ['user_id']; referencedRelation: 'users'; referencedColumns: ['id'] },
        ];
      };
      staff_profiles: {
        Row: {
          id: string;
          display_name: string;
          jira_account_id: string;
          telegram_chat_id: string;
          telegram_username: string | null;
          telegram_notifications_enabled: boolean;
          role: 'operator' | 'translator' | 'notary_partner' | 'admin';
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          display_name: string;
          jira_account_id: string;
          telegram_chat_id: string;
          telegram_username?: string | null;
          telegram_notifications_enabled?: boolean;
          role: 'operator' | 'translator' | 'notary_partner' | 'admin';
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          display_name?: string;
          jira_account_id?: string;
          telegram_chat_id?: string;
          telegram_username?: string | null;
          telegram_notifications_enabled?: boolean;
          role?: 'operator' | 'translator' | 'notary_partner' | 'admin';
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      notification_log: {
        Row: {
          id: string;
          event_id: string;
          order_id: string;
          jira_issue_key: string | null;
          recipient_profile_id: string | null;
          channel: string;
          template: string;
          status: 'pending' | 'sent' | 'failed' | 'skipped';
          provider_message_id: string | null;
          error: string | null;
          created_at: string;
          sent_at: string | null;
        };
        Insert: {
          id?: string;
          event_id: string;
          order_id: string;
          jira_issue_key?: string | null;
          recipient_profile_id?: string | null;
          channel?: string;
          template: string;
          status?: 'pending' | 'sent' | 'failed' | 'skipped';
          provider_message_id?: string | null;
          error?: string | null;
          created_at?: string;
          sent_at?: string | null;
        };
        Update: {
          status?: 'pending' | 'sent' | 'failed' | 'skipped';
          provider_message_id?: string | null;
          error?: string | null;
          sent_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'notification_log_order_id_fkey'; columns: ['order_id']; referencedRelation: 'jobs'; referencedColumns: ['id'] },
          { foreignKeyName: 'notification_log_recipient_profile_id_fkey'; columns: ['recipient_profile_id']; referencedRelation: 'staff_profiles'; referencedColumns: ['id'] },
        ];
      };
      fiscal_receipts: {
        Row: {
          id: string;
          job_id: string;
          document_id: string;
          payment_transaction_id: string;
          provider: string;
          provider_environment: 'test' | 'production';
          provider_receipt_id: string | null;
          provider_shift_id: string | null;
          provider_cashbox_id: string | null;
          fiscal_sign: string | null;
          fiscal_url: string | null;
          amount_kzt: number;
          currency: string;
          operation_type: 'sale' | 'refund' | 'correction';
          status: 'pending_manual' | 'blocked_by_config' | 'pending' | 'issued' | 'failed' | 'retry_required' | 'canceled';
          customer_email: string | null;
          customer_phone: string | null;
          receipt_payload_sanitized: Json | null;
          provider_response_sanitized: Json | null;
          error_code: string | null;
          error_message: string | null;
          retry_count: number;
          issued_at: string | null;
          failed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          document_id: string;
          payment_transaction_id: string;
          provider?: string;
          provider_environment?: 'test' | 'production';
          provider_receipt_id?: string | null;
          provider_shift_id?: string | null;
          provider_cashbox_id?: string | null;
          fiscal_sign?: string | null;
          fiscal_url?: string | null;
          amount_kzt: number;
          currency?: string;
          operation_type?: 'sale' | 'refund' | 'correction';
          status?: 'pending_manual' | 'blocked_by_config' | 'pending' | 'issued' | 'failed' | 'retry_required' | 'canceled';
          customer_email?: string | null;
          customer_phone?: string | null;
          receipt_payload_sanitized?: Json | null;
          provider_response_sanitized?: Json | null;
          error_code?: string | null;
          error_message?: string | null;
          retry_count?: number;
          issued_at?: string | null;
          failed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: 'pending_manual' | 'blocked_by_config' | 'pending' | 'issued' | 'failed' | 'retry_required' | 'canceled';
          provider_receipt_id?: string | null;
          provider_shift_id?: string | null;
          provider_cashbox_id?: string | null;
          fiscal_sign?: string | null;
          fiscal_url?: string | null;
          provider_response_sanitized?: Json | null;
          error_code?: string | null;
          error_message?: string | null;
          retry_count?: number;
          issued_at?: string | null;
          failed_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: 'fiscal_receipts_job_id_fkey'; columns: ['job_id']; referencedRelation: 'jobs'; referencedColumns: ['id'] },
          { foreignKeyName: 'fiscal_receipts_document_id_fkey'; columns: ['document_id']; referencedRelation: 'documents'; referencedColumns: ['id'] },
          { foreignKeyName: 'fiscal_receipts_payment_transaction_id_fkey'; columns: ['payment_transaction_id']; referencedRelation: 'payment_transactions'; referencedColumns: ['id'] },
        ];
      };
      refund_transactions: {
        Row: {
          id: string;
          job_id: string;
          payment_transaction_id: string;
          provider: string;
          provider_environment: 'test' | 'production';
          provider_refund_id: string | null;
          provider_transaction_id: string | null;
          refund_amount_kzt: number;
          currency: string;
          status: 'requested' | 'pending' | 'succeeded' | 'failed' | 'requires_review' | 'pending_manual' | 'canceled';
          reason: string;
          operator_id: string | null;
          idempotency_key: string;
          fiscal_refund_receipt_id: string | null;
          provider_response_sanitized: Json | null;
          error_code: string | null;
          error_message: string | null;
          requested_at: string;
          processed_at: string | null;
          failed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          payment_transaction_id: string;
          provider?: string;
          provider_environment?: 'test' | 'production';
          provider_refund_id?: string | null;
          provider_transaction_id?: string | null;
          refund_amount_kzt: number;
          currency?: string;
          status?: 'requested' | 'pending' | 'succeeded' | 'failed' | 'requires_review' | 'pending_manual' | 'canceled';
          reason: string;
          operator_id?: string | null;
          idempotency_key: string;
          fiscal_refund_receipt_id?: string | null;
          provider_response_sanitized?: Json | null;
          error_code?: string | null;
          error_message?: string | null;
          requested_at?: string;
          processed_at?: string | null;
          failed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: 'requested' | 'pending' | 'succeeded' | 'failed' | 'requires_review' | 'pending_manual' | 'canceled';
          provider_refund_id?: string | null;
          fiscal_refund_receipt_id?: string | null;
          provider_response_sanitized?: Json | null;
          error_code?: string | null;
          error_message?: string | null;
          processed_at?: string | null;
          failed_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: 'refund_transactions_job_id_fkey'; columns: ['job_id']; referencedRelation: 'jobs'; referencedColumns: ['id'] },
          { foreignKeyName: 'refund_transactions_payment_transaction_id_fkey'; columns: ['payment_transaction_id']; referencedRelation: 'payment_transactions'; referencedColumns: ['id'] },
          { foreignKeyName: 'refund_transactions_fiscal_refund_receipt_id_fkey'; columns: ['fiscal_refund_receipt_id']; referencedRelation: 'fiscal_receipts'; referencedColumns: ['id'] },
        ];
      };
      partner_applications: {
        Row: {
          id: string;
          partner_type: 'translator' | 'notary' | 'agency' | 'visa_center' | 'migration_consultant' | 'education_agency' | 'legal_firm' | 'corporate' | 'other';
          name: string;
          email: string;
          phone: string | null;
          organization: string | null;
          message: string | null;
          ref_code: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          status: 'pending' | 'reviewing' | 'approved' | 'rejected';
          jira_issue_key: string | null;
          jira_issue_url: string | null;
          jira_sync_status: 'pending' | 'synced' | 'failed';
          jira_error: string | null;
          jira_created_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          partner_type: 'translator' | 'notary' | 'agency' | 'visa_center' | 'migration_consultant' | 'education_agency' | 'legal_firm' | 'corporate' | 'other';
          name: string;
          email: string;
          phone?: string | null;
          organization?: string | null;
          message?: string | null;
          ref_code?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          status?: 'pending' | 'reviewing' | 'approved' | 'rejected';
          jira_issue_key?: string | null;
          jira_issue_url?: string | null;
          jira_sync_status?: 'pending' | 'synced' | 'failed';
          jira_error?: string | null;
          jira_created_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: 'pending' | 'reviewing' | 'approved' | 'rejected';
          jira_issue_key?: string | null;
          jira_issue_url?: string | null;
          jira_sync_status?: 'pending' | 'synced' | 'failed';
          jira_error?: string | null;
          jira_created_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      partners: {
        Row: {
          id: string;
          application_id: string | null;
          partner_type: string;
          name: string;
          email: string;
          organization: string | null;
          referral_code: string;
          commission_rate: number;
          is_active: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          application_id?: string | null;
          partner_type: string;
          name: string;
          email: string;
          organization?: string | null;
          referral_code: string;
          commission_rate?: number;
          is_active?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          partner_type?: string;
          name?: string;
          email?: string;
          organization?: string | null;
          referral_code?: string;
          commission_rate?: number;
          is_active?: boolean;
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: 'partners_application_id_fkey'; columns: ['application_id']; referencedRelation: 'partner_applications'; referencedColumns: ['id'] },
        ];
      };
      partner_referrals: {
        Row: {
          id: string;
          partner_id: string;
          job_id: string | null;
          user_id: string | null;
          ref_code: string;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          captured_at: string;
          order_completed_at: string | null;
          commission_base_kzt: number | null;
          commission_kzt: number | null;
          status: 'pending' | 'completed' | 'excluded' | 'refunded';
          payout_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          partner_id: string;
          job_id?: string | null;
          user_id?: string | null;
          ref_code: string;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          captured_at?: string;
          order_completed_at?: string | null;
          commission_base_kzt?: number | null;
          commission_kzt?: number | null;
          status?: 'pending' | 'completed' | 'excluded' | 'refunded';
          payout_id?: string | null;
          created_at?: string;
        };
        Update: {
          order_completed_at?: string | null;
          commission_base_kzt?: number | null;
          commission_kzt?: number | null;
          status?: 'pending' | 'completed' | 'excluded' | 'refunded';
          payout_id?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'partner_referrals_partner_id_fkey'; columns: ['partner_id']; referencedRelation: 'partners'; referencedColumns: ['id'] },
          { foreignKeyName: 'partner_referrals_job_id_fkey'; columns: ['job_id']; referencedRelation: 'jobs'; referencedColumns: ['id'] },
          { foreignKeyName: 'partner_referrals_user_id_fkey'; columns: ['user_id']; referencedRelation: 'users'; referencedColumns: ['id'] },
        ];
      };
      partner_payouts: {
        Row: {
          id: string;
          partner_id: string;
          period_start: string;
          period_end: string;
          gross_kzt: number;
          net_kzt: number;
          referral_count: number;
          status: 'pending' | 'approved' | 'paid' | 'cancelled';
          payment_details: Json | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          partner_id: string;
          period_start: string;
          period_end: string;
          gross_kzt?: number;
          net_kzt?: number;
          referral_count?: number;
          status?: 'pending' | 'approved' | 'paid' | 'cancelled';
          payment_details?: Json | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          gross_kzt?: number;
          net_kzt?: number;
          referral_count?: number;
          status?: 'pending' | 'approved' | 'paid' | 'cancelled';
          payment_details?: Json | null;
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: 'partner_payouts_partner_id_fkey'; columns: ['partner_id']; referencedRelation: 'partners'; referencedColumns: ['id'] },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
