// Auto-generated by: supabase gen types --project-id qziwyakewuneokzdpoyf --schema public
// Re-run after schema changes: supabase gen types --project-id qziwyakewuneokzdpoyf --schema public > src/types/supabase.ts
// Requires: supabase login --token <YOUR_PAT>

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      documents: {
        Row: {
          id: string;
          user_id: string;
          filename: string;
          original_file_size: number;
          file_key: string;
          source_language: string;
          target_language: string;
          document_type: string;
          status: 'uploading' | 'processing' | 'completed' | 'failed';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          filename: string;
          original_file_size: number;
          file_key: string;
          source_language: string;
          target_language: string;
          document_type: string;
          status: 'uploading' | 'processing' | 'completed' | 'failed';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          filename?: string;
          original_file_size?: number;
          file_key?: string;
          source_language?: string;
          target_language?: string;
          document_type?: string;
          status?: 'uploading' | 'processing' | 'completed' | 'failed';
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: 'documents_user_id_fkey'; columns: ['user_id']; referencedRelation: 'users'; referencedColumns: ['id'] },
        ];
      };
      jobs: {
        Row: {
          id: string;
          document_id: string;
          status: 'queued' | 'ocr_in_progress' | 'ocr_completed' | 'translation_in_progress' | 'pdf_rendering' | 'completed' | 'failed';
          error_message: string | null;
          progress_percent: number;
          priority: number;
          payment_source: 'ton_payment' | 'subscription' | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          document_id: string;
          status: 'queued' | 'ocr_in_progress' | 'ocr_completed' | 'translation_in_progress' | 'pdf_rendering' | 'completed' | 'failed';
          error_message?: string | null;
          progress_percent?: number;
          priority?: number;
          payment_source?: 'ton_payment' | 'subscription' | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          document_id?: string;
          status?: 'queued' | 'ocr_in_progress' | 'ocr_completed' | 'translation_in_progress' | 'pdf_rendering' | 'completed' | 'failed';
          error_message?: string | null;
          progress_percent?: number;
          priority?: number;
          payment_source?: 'ton_payment' | 'subscription' | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: 'jobs_document_id_fkey'; columns: ['document_id']; referencedRelation: 'documents'; referencedColumns: ['id'] },
        ];
      };
      ocr_results: {
        Row: {
          id: string;
          job_id: string;
          markdown: string;
          page_count: number;
          detected_language: string | null;
          provider: 'mistral' | 'google_docai';
          created_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          markdown: string;
          page_count: number;
          detected_language?: string | null;
          provider: 'mistral' | 'google_docai';
          created_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          markdown?: string;
          page_count?: number;
          detected_language?: string | null;
          provider?: 'mistral' | 'google_docai';
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: 'ocr_results_job_id_fkey'; columns: ['job_id']; referencedRelation: 'jobs'; referencedColumns: ['id'] },
        ];
      };
      translations: {
        Row: {
          id: string;
          job_id: string;
          translated_markdown: string;
          translated_pdf_key: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          translated_markdown: string;
          translated_pdf_key: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          translated_markdown?: string;
          translated_pdf_key?: string;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: 'translations_job_id_fkey'; columns: ['job_id']; referencedRelation: 'jobs'; referencedColumns: ['id'] },
        ];
      };
      wallet_links: {
        Row: {
          id: string;
          user_id: string;
          address: string;
          address_raw: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          address: string;
          address_raw: string;
          created_at?: string;
        };
        Update: {
          address?: string;
          address_raw?: string;
        };
        Relationships: [
          { foreignKeyName: 'wallet_links_user_id_fkey'; columns: ['user_id']; referencedRelation: 'users'; referencedColumns: ['id'] },
        ];
      };
      ton_payments: {
        Row: {
          id: string;
          user_id: string;
          document_id: string;
          job_id: string;
          amount_nanoton: string;
          amount_usd: number;
          ton_price_usd: number;
          status: 'pending' | 'completed' | 'expired' | 'failed';
          tx_hash: string | null;
          wallet_address: string | null;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          document_id: string;
          job_id: string;
          amount_nanoton: number | string;
          amount_usd: number;
          ton_price_usd: number;
          status?: 'pending' | 'completed' | 'expired' | 'failed';
          tx_hash?: string | null;
          wallet_address?: string | null;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          status?: 'pending' | 'completed' | 'expired' | 'failed';
          tx_hash?: string | null;
          wallet_address?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'ton_payments_user_id_fkey'; columns: ['user_id']; referencedRelation: 'users'; referencedColumns: ['id'] },
          { foreignKeyName: 'ton_payments_document_id_fkey'; columns: ['document_id']; referencedRelation: 'documents'; referencedColumns: ['id'] },
          { foreignKeyName: 'ton_payments_job_id_fkey'; columns: ['job_id']; referencedRelation: 'jobs'; referencedColumns: ['id'] },
        ];
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          plan: 'basic' | 'pro';
          status: 'pending' | 'active' | 'expired' | 'cancelled';
          documents_limit: number;
          documents_used: number;
          amount_nanoton: string | null;
          amount_usd: number | null;
          ton_price_usd: number | null;
          tx_hash: string | null;
          started_at: string | null;
          expires_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          plan: 'basic' | 'pro';
          status?: 'pending' | 'active' | 'expired' | 'cancelled';
          documents_limit: number;
          documents_used?: number;
          amount_nanoton?: number | string | null;
          amount_usd?: number | null;
          ton_price_usd?: number | null;
          tx_hash?: string | null;
          started_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
        };
        Update: {
          status?: 'pending' | 'active' | 'expired' | 'cancelled';
          documents_used?: number;
          tx_hash?: string | null;
          started_at?: string | null;
          expires_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'subscriptions_user_id_fkey'; columns: ['user_id']; referencedRelation: 'users'; referencedColumns: ['id'] },
        ];
      };
      payments: {
        Row: {
          id: string;
          user_id: string;
          stripe_charge_id: string;
          amount_cents: number;
          document_id: string | null;
          status: 'pending' | 'completed' | 'failed';
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          stripe_charge_id: string;
          amount_cents: number;
          document_id?: string | null;
          status: 'pending' | 'completed' | 'failed';
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          stripe_charge_id?: string;
          amount_cents?: number;
          document_id?: string | null;
          status?: 'pending' | 'completed' | 'failed';
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: 'payments_user_id_fkey'; columns: ['user_id']; referencedRelation: 'users'; referencedColumns: ['id'] },
          { foreignKeyName: 'payments_document_id_fkey'; columns: ['document_id']; referencedRelation: 'documents'; referencedColumns: ['id'] },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
