-- Migration 0018: Refund transactions table
-- Tracks operator-initiated refund requests and their processing state.
-- No public user endpoint for refunds. All refunds go through operator flow.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Create refund_transactions table
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.refund_transactions (
  id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Core references
  job_id                      UUID NOT NULL REFERENCES public.jobs(id),
  payment_transaction_id      UUID NOT NULL REFERENCES public.payment_transactions(id),

  -- Provider
  provider                    TEXT NOT NULL DEFAULT 'halyk_epay',
  provider_environment        TEXT NOT NULL DEFAULT 'test'
                              CHECK (provider_environment IN ('test', 'production')),
  provider_refund_id          TEXT,
  provider_transaction_id     TEXT,

  -- Amount (positive integers, KZT only)
  refund_amount_kzt           INTEGER NOT NULL CHECK (refund_amount_kzt > 0),
  currency                    TEXT NOT NULL DEFAULT 'KZT' CHECK (currency = 'KZT'),

  -- Lifecycle status
  -- requested:       operator created the refund request; not yet sent to provider
  -- pending:         sent to provider; awaiting confirmation
  -- succeeded:       provider confirmed refund
  -- failed:          provider returned error
  -- requires_review: ambiguous response; needs manual investigation
  -- pending_manual:  no provider integration; operator must process via Halyk cabinet
  -- canceled:        operator canceled before processing
  status                      TEXT NOT NULL DEFAULT 'pending_manual'
                              CHECK (status IN (
                                'requested', 'pending', 'succeeded', 'failed',
                                'requires_review', 'pending_manual', 'canceled'
                              )),

  -- Request metadata
  reason                      TEXT NOT NULL,
  operator_id                 TEXT,                    -- staff_profiles.id or email, for audit
  idempotency_key             TEXT NOT NULL UNIQUE,    -- prevents duplicate submission

  -- Linked fiscal refund receipt (FK to fiscal_receipts.id, nullable until issued)
  fiscal_refund_receipt_id    UUID REFERENCES public.fiscal_receipts(id),

  -- Sanitised provider response (no card data)
  provider_response_sanitized JSONB,

  -- Error tracking
  error_code                  TEXT,
  error_message               TEXT,

  -- Timestamps
  requested_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at                TIMESTAMPTZ,
  failed_at                   TIMESTAMPTZ,
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.refund_transactions IS
  'Operator-initiated refund requests. No public endpoint — all refunds via operator flow.';
COMMENT ON COLUMN public.refund_transactions.idempotency_key IS
  'Unique key to prevent double refund submission. Generated by the operator service.';
COMMENT ON COLUMN public.refund_transactions.status IS
  'pending_manual: no Halyk refund adapter active; process via Halyk merchant cabinet.';
COMMENT ON COLUMN public.refund_transactions.operator_id IS
  'Identifier of the operator who initiated the refund (for audit trail).';

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Indexes for reconciliation and audit
-- ─────────────────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_refund_transactions_payment_id
  ON public.refund_transactions (payment_transaction_id);

CREATE INDEX IF NOT EXISTS idx_refund_transactions_status
  ON public.refund_transactions (status, created_at);

CREATE INDEX IF NOT EXISTS idx_refund_transactions_job_id
  ON public.refund_transactions (job_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Helper: compute refundable amount for a payment
-- Used by the refund service to validate refund amount before insertion.
-- Returns: { total_paid, total_refunded, refundable }
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_refundable_amount(
  p_payment_transaction_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_paid_amount     INTEGER;
  v_refunded_amount INTEGER;
BEGIN
  -- Get paid amount (must be a paid transaction)
  SELECT COALESCE(amount::INTEGER, 0)
    INTO v_paid_amount
    FROM public.payment_transactions
    WHERE id = p_payment_transaction_id
      AND status = 'paid';

  IF NOT FOUND OR v_paid_amount = 0 THEN
    RETURN jsonb_build_object(
      'ok', false,
      'error', 'payment_not_paid',
      'total_paid', 0,
      'total_refunded', 0,
      'refundable', 0
    );
  END IF;

  -- Sum succeeded refunds for this payment
  SELECT COALESCE(SUM(refund_amount_kzt), 0)
    INTO v_refunded_amount
    FROM public.refund_transactions
    WHERE payment_transaction_id = p_payment_transaction_id
      AND status = 'succeeded';

  RETURN jsonb_build_object(
    'ok', true,
    'total_paid', v_paid_amount,
    'total_refunded', v_refunded_amount,
    'refundable', GREATEST(0, v_paid_amount - v_refunded_amount)
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.get_refundable_amount FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_refundable_amount FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_refundable_amount FROM authenticated;
GRANT EXECUTE ON FUNCTION public.get_refundable_amount TO service_role;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. RLS: no user access to refund_transactions
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.refund_transactions ENABLE ROW LEVEL SECURITY;

-- Service role bypasses RLS. No user-facing policies — refunds are operator-only.
-- (No SELECT policy for authenticated users — clients do not see raw refund records.)
